BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/Client.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, Queue.swift
Step 2: 우선순위와 다중처리
- 고객 우선순위 구현(VVIP, VIP, 일반)
- 은행원 3명 근무
- 은행 업무 구현(대출, 예금)
- 우선순위에 따른 업무 처리
리뷰 부탁드립니다!
=> (Jacob & Sodae) Step 2 우선순위와 다중처리

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/BankClerk.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/Enum.swift, BankManagerConsoleApp/BankManagerConsoleApp/Print.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
정말 은행업무를 보는 것 처럼 손님(Customer)들한테 대기표(BankManager에서)를 주고 창구(BankClerk)에서 불이 들어올 때 고객을 한명씩 받는 것을 구현하고 싶었습니다.
Customer는 대기번호와 처리시간을 갖습니다.
BankManager에서 손님의 수를 랜덤으로받아 waitingList 배열에 추가합니다. 
BankManager에서 은행원의 수만큼 창구를 만듭니다.
bankManager에서 첫번째 손님을 할당합니다. <- 이부분은 창구에서 보충설명 하겠습니다.
고민했던 부분
창구(BankClerk)에서 일이 끝나면 뱅크매니저의 대기열에있던 손님 하나를 창구의-손님으로 데려옵니다.
working을 프로퍼티로 갖고 false일 때 손님을 받기 위해 didSet을 썼더니 처음 시작할 때 working의 상태가 이미 false인 상태여서 작동하지 않았습니다. (true에서 false로 바뀌어야 작동) -> 뱅크매니저에서 첫손님은 직접 할당합니다.
working의 상태를 바꿔줘야 했기 때문에 창구의 메서드를 이용해 startWork과 finishWork로 구분해  working의 상태를 각각 true, false가 되도록 했습니다. 
처음 고객을 직접 할당하지 않아도 돌아갈 수 있게 구현할 수 있는 방법이 있을까요?
처음 프로젝트를 받았을 때 dispatchQueue 혹은 operationQueue 와 함께 nofiticationCenter 혹은 KVO를 써보고 싶었는데 공부가 많이 부족한 것 같습니다.
Queue는 커녕 type설계하는 부분에서도 어떤 프로퍼티를 어디에 속하게 해야할지, 또 …
=> Step1 sole

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
찌로와 같은 팀인데 PR은 따로 보내기로 하였습니다. 리뷰 부탁드려요~
1. BankManager 클래스 구현.
- 은행원 클래스(Banker)은 담당 고객을 프로퍼리로 갖고 있으며, performTask method는 usleep함수를 이용하여 대기하도록해서 구현하였습니다.
- 고객 클래스(Customer)는 대기 번호를 프로퍼티로 갖고 있습니다. 
- DispatchQueue를 이용하여 은행원이 다른 쓰레드에서 업무를 수행하도록 구현하였습니다.
2. Console App 구현.
- BankManger 클래스를 이용하여 구현하였습니다.
- 고객의 수를 10~30의 랜덤값을 생성하여 BankManager객체를 생성하도록 구현하였습니다.
=> Step 1 : Console App 구현 (Bam)

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/Enum/BankStringCollection.swift, BankManagerConsoleApp/BankManagerConsoleApp/Error/BankError.swift, BankManagerConsoleApp/BankManagerConsoleApp/Error/StringFormattingError.swift, BankManagerConsoleApp/BankManagerConsoleApp/Extension/StringExtension.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
코드리뷰 부탁드립니다!! 🙏
[구현 사항]
1. 손님의 업무에 우선순위와 종류가 생겨서 이를 Enum 타입으로 생성
2. main.swift에서 랜덤으로 번호, 우선순위, 업무의 종류를 가지는 손님들을 Init 해주도록 구현 (이때 init후에 우선순위에 맞춰 정렬)
3. BankManager는 performanceTaks()에서 업무 순위에 따라서 해당 업무를 처리하도록 수정
4. BankManager를 3명으로 수정하고 각각 dispatchQueue를 가질 수 있도록 BankManager 타입 수정
5. Bank에서 BankManager에게 손님을 할당해주는 부분에서 비 동기적으로 손님을 할당해 줄 수 있도록 구현
5-1. 이때 은행원 한 명당 한 명의 손님을 받을 수 있으므로 DispatchSemaphore를 사용해서 은행원에게 할당되는 손님의 수를 제한하였습니다.
5-2. 또한 은행원들이 모든 업무가 끝났을 때 은행의 마지막 출력문구가 출력되게하기 위해서 DispatchGroup을 사용했습니다. 
6. 기존에 performTask()에서는 customer.priority, customer.waitNumber, customer.task를 넘겼다면 한 명의 손님을 넘길 수 있도록 수정
현재 비 동기로 처리해주는 로직에 대해서 그림과 글로 표현해봤는데 제가 설계한 것이 실제로 코드로 맞게 작성이 되었는지 확인해주시면 감사하겠습니다!!
=> Step 2 : 우선순위와 다중처리 Jake

BankClerk.swift, BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/TaskTypes.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankerMessage.swift, InputStateMessage.swift
- Customer 구조체 추가 
- 은행원(assignedBankClerk)을 3명으로 증원
- TaskType 타입 추가 (deposit, loan) 
- 고객을 생성할 때 고객등급(customerClass)와 고객업무(customerTask)를 랜덤하게 (allcases.randomElement()) 설정
- 고객 정렬을 하기 위한 우선순위 연산 부분은 Comparable protocol 사용
- 고객과 은행원을 객체를 생성하여 배열에 저장 
- dispatch Group, wait()을 사용하여 메인 스레드가 다른 스레드를 기다려주도록 구현
=> Step 2 : 우선순위와 다중처리 (Glenn, 태태)

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Clerk.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/HeadOffice.swift, BankManagerConsoleApp/BankManagerConsoleApp/PriorityQueue.swift
고객을 등급 우선순위로 가져오기 위해
내부적으로 heap 을 사용하는 우선순위 큐를 이용하여 고객 대기열을 만들었습니다.
=> STEP 2 찌루루

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/BankHeadquarter.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/Enum/BankStringCollection.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
step3 구현 완료했습니다!!
코드 리뷰 부탁드려요~
[구현사항]
1. 은행본사(BankHeadquarter) 타입 구현
1-1. 이때 본사는 하나이므로 singleton 타입으로 구현하였습니다.
1-2. serialQueue를 가지고 있고, 대출 심사를 진행하는 함수를 가지고 있습니다.
2. BankManager에서 customer의 업무에 따라서 해당 일을 처리하도록 구현
2-1. 대출 업무인 경우에는 서류 검토, 대출 심사 요청, 대출 실행 3가지의 함수로 구현하여 진행할 수 있도록 구현하였습니다.
2-2. 예금 업무인 경우에도 하나의 함수로 작성하여 해당 업무를 처리할 수 있도록 구현
3. Enum 타입들을 관련된 타입에 위치시켰습니다. 
감사합니다!!
=> Step3 Jake

BankClerk.swift, BankHeadOffice.swift, BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, Client.swift
- BankHeadOffice
- 싱글턴 패턴으로 구현 
- 은행원이 대출 심사를 요청하면 순서대로 처리
- 대출심사 완료되면 NotificationCenter로 해당 은행원에게 대출심사 완료 알려줌
- BankClerk
- 대출 과정 세분화
- 은행에게 대출심사 요청할 때, 대출심사 완료를 NotificatonCenter로 받도록 옵저버로 등록하고, 대출심사 완료되면 옵저버 제거
=> Step 3 - Sodae & Jacob

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerUIApp/BankManagerUIApp.xcodeproj/project.pbxproj, BankManagerUIApp/BankManagerUIApp/Bank.swift, BankManagerUIApp/BankManagerUIApp/BankManageable.swift, BankManagerUIApp/BankManagerUIApp/BankManager.swift, Client.swift
@AppleCEO 
안녕하세요 `도미닉`!
조금이나마 빠른 피드백을 받고 싶어서 늦은 시간이지만 PR을 올립니다 ! 
Step1의 요구사항을 따라 구현해 봤어요
- 콘솔 구현
은행원 1명에 대해 operation, operationQueue(쓰레드 1개 지정)로 동기적인 처리를 구현해봤어요 
- 타입 구현
추후 앱을 구현하기 위해 타입을 `Bank`, `BankManager`, `Client` 로 나눠서 구현하고 `BankManageable` 프로토콜을 통해 `BankManager` 의 기능을 추상화해봤어요 
------
<br/>
1. wait 
```swift
waitUntilFinished() // operation
waitUntilAllOperationsAreFinished() // operationQueue
```
- 콘솔
`operation` 이 한 명의 고객이라고 생각하고, 한 명의 고객이 동기적으로 작동하기 위해서 `maxConcurrentOperationCount = 1` 로 스레드를 1개로 지정했어요
여기서 문제점은 한 명의 작업을 동기적으로 기다리기 위해 operation을 대기하는 `waitUntilFinished()` 을 사용하면 `시작시작 완료완료` 곂치는 문제가 발생했어요 
그래서 operationQueue를 기다리는 `waitUntilAllOperationsAreFinished()` 을 사용하니 요구사항에 맞게 동기적으로 동작했어요. (시작완료 시작완료)
왜 `waitUntilFinished()` 를 사용하면 비동기적인 상황이 벌어지는지 알고 싶어요 !
<br/>
2. lazy …
=> [Step 1] James, Fezz

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/Constatnt/ClientGrade.swift, BankManagerConsoleApp/Constatnt/ClientTask.swift, BankManagerConsoleApp/Type/BankManager.swift, BankManagerConsoleApp/Type/Banker.swift, BankManagerConsoleApp/Type/Client.swift
@wonhee009  
안녕하세요 STEP 2 PR 드립니다!
재귀함수를 대체할 방법을 고민하였습니다.     
재귀함수를 대체할 방법으로 while true를 이용한 무한 루프와       
operation을 이용해서 쓰레드 안에 startBank() 함수를 넣는 방법을 생각해봤습니다.      
operation을 이용한 방법은 Debugging시에 Thread가 계속 생성되는 것을 확인하였습니다.     
Thread를 이용한 방법은 리소스를 낭비한다고 생각하여 무한루프를 이용한 방법을 선택하였습니다.    
Thread가 현재 생성되어있는 수와 재귀함수의 call stack을 확인하는 방식으로      
재귀함수를 몇번 호출하게 한 후에     
마우스를 이용해서 코드에 breakpoint를 걸어서     
Debug navigator를 이용해서 call stack과 Thread를 확인했는데     
이 방법이 적절한 방법이었는지 조언을 얻고 싶습니다.        
감사합니다!
=> [STEP 2] JM, Summer

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/BankTeller.swift, BankManagerConsoleApp/BankManagerConsoleApp/ClientLinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Data.swift, BankManagerConsoleApp/BankManagerConsoleApp/Error.swift, BankManagerConsoleApp/BankManagerConsoleApp/Protocol.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
@corykim0829
Step1 첫 PR 올립니다~!
1. BankManager.siwft : Bank 클래스 구현
- startService()를 통하여 프로그램 시작
- showInitialMenu()를 통해 초기화면 출력
- receiverUserInput()를 통해 유저입력
- pickRandomClientNumber()를 통해 랜덤client 수 도출
- enqueueClient()를 통해 랜덤 client 수 만큼 client에 enqueue
- conductService()를 통해'1'을 선택했을경우 전달된 은행원이 업무시작
- sumOfficeHours()를 통해 고객당 0.7초의 작업시간 계산
2. Data.swift : 프로그램에서 사용되는 문자열 선언
3. ClientLinkedList.swift : Node, LinkedList를 사용하여 Queue 구현
4. BankTeller.swift : 은행원(Teller)타입 구현
- announceServiceStart()를 통해 업무시작 알림
- announceServiceFinish()를 통해 업무종료 알림
- 잘못된 입력이 들어오거나  은행업무가 끝난 후 startService()의 코드를 다시 동작 시킬때 
while문과 재귀함수 중 무한루프에 빠질 위험성을 고려하여 재귀함수를 사용하여 구현하였습니다.
- Step1에서는 비동기처리를 해주지않아도 된다고 판단하여 LinkedList를 활용한 Queue를 구현해주었고 Client의 Type을 사용하기 위해서 양방향 Node를 구현해주었습니다.
- 한 고객당 작업에 delay를 주기위하여 …
=> STEP1 - Alan, Bobby

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankDirector.swift, BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/Task.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
안녕하세요 하이디! 😁 벌써 4월 마지막 날이에요 곧 5월이 되니 시간이 정말 빠르죠..? 
오늘 야곰 스타터 캠프 1기 선배들이 수료하는 모습을 보면서 기분이 싱숭생숭해요
저와 써니도 2기를 수료하는 날이 올 텐데.. 그 때 까지 열심히 해보겠습니다 ! 잘 부탁드립니다 ! 🤩
---
<br>
<br>
<br>
---
Step1에서부터 operationQueue를 적용해봤는데요.
operationQueue를 처음 사용해 보는지라.. 많이 어색하네요 😭
여러 가지 개념들도 공부해보고 고민을 해봤어요!
**1. OperationQueue를 구현하는데 필수적으로 사용해야 하는 메소드가 있는가?**
operationQueue 자료를 찾다보니 아래 내용을 발견했어요.
_If you are creating a concurrent operation, you need to override the following methods and properties at a minimum:_
* start()
* isAsynchronous
* isExecuting
* isFinished
Operation Queue가 단순히 큐를 만들고 addOperation하면 되는게 아니라, 저 메소드들을 다 써줘야 하는건지? 의문이 들었어요.
그래서 다른 캠퍼에게 물어보니 꼭 저 메서드들을 사용해야 할 필요가 없다는 걸 알게 됐어요 ! (지금 당장 필요한게 아니라면)
<br>
**2. operationQueue를 구현하는 방법이 뭐가 있는지?**
addOperation BlockOperation 으로 바로 만들거나, Operation 객체를 상속 …
=> 은행창구 매니저 [STEP 1] Ian, Sunny

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/HandleCustomerOperation.swift
@O-O-wl
안녕하세요 :) Step3 PR을 보냅니다!
<br/>
<br/>
- Step3와 Step2의 가장 큰 차이는 각 은행 창구에서 업무를 처리하는 시간이 일괄적으로 정해진 것이 아니라 (대출의 경우) 본사의 업무 처리 속도에 영향을 받는다는 것입니다. 본사의 업무가 기능요구서에 따라 동시에 한 개만 진행될 수 있으므로 자원을 독점하기 위해 두가지 방식을 생각했습니다.
>1. 뮤텍스
>2. 세마포어
구현상에 큰 차이가 있을 것 같지는 않고 현재 기능 요구서는 본사의 자원을 한개의 은행 창구만 점유할 수 있는 구조이기 때문에 뮤텍스 개념으로 접근 가능할 것 같습니다. 하나의 업무가 자원을 할당 받았을 때 Lock을 거는 개념으로 생각할 수 있기 때문입니다. 하지만 본사에서 동시 처리 가능한 대출 업무의 수가 늘어날 수 있기 때문에 확장 가능한 세마포어로 구현했습니다. 즉, semaphoreValue를 설정해 업무를 처리할 수 있는 자원이 없는 동안(semaphoreValue < 0) 무한 반복을 통해 진행을 막고, 이전 업무가 처리되어 다시 semaphoreValue가 사용 가능한 수치가 되면 다음 작업을 수행하는 식으로 구현했습니다.
<br/>
- 구조를 보면 BankHeadOffice는 static만을 갖는 name space역할을 한다고 생각합니다. 기존과 비슷한 고민인데 HandleCustomerOperation 클래스에서 BankHeadOffice.loanJudgement 메소드를 사용함으로써 static 변수인 semaphoreValue의 값을 변경시키는데 이 구조가 두 객체의 커플링을 …
=> [Step3] Jay, Neph 

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/Constatnt/BankerTask.swift, BankManagerConsoleApp/Constatnt/ClientTask.swift, BankManagerConsoleApp/Constatnt/UserInformationKey.swift, BankManagerConsoleApp/Type/BankManager.swift, BankManagerConsoleApp/Type/Banker.swift, BankManagerConsoleApp/Type/Client.swift, BankManagerConsoleApp/Type/HeadOffice.swift
@wonhee009 
안녕하세요 STEP 3 PR 드립니다!
어떻게 코드에 대출심사 완료 조건이 성립할 때까지 delay를 걸지 고민하였습니다.
```swift
operationQueue.isSuspended = true
NotificationCenter.default.post(name: notificationName, object: nil, userInfo: [UserInformationKey.banker:self, UserInformationKey.client: client])
operationQueue.addOperation {}
operationQueue.waitUntilAllOperationsAreFinished()
```
위의 코드에서 isSuspended = true를 통해서 OperationQueue의 작동을 멈추고  
Notification을 호출하고
operationQueue에 공백의 operation 코드를 집어넣어 operationQueue가 빈 큐가 아니게 하였습니다.      
빈 큐가 아니므로 waitUntilOperationAreFinished를 이용하여 delay를 걸었고          
Notification을 호출한 후에 호출되는 객체의 함수에서 대출심사를 완료한 후에        
isSuspended = false를 해줘서 operationQueue를 작동시켜서 waitUntilOperationAreFinished를 빠져나오도록 했습니다.    
delay를 얻는 방법으로 operationQueue의 waitUntilOperationAreFinished를 이용하였는데 …
=> [STEP 3] JM, Summer

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankError.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankTask.swift, BankManagerConsoleApp/BankManagerConsoleApp/Client.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
@myssun0325 
메이슨 안녕하세요🤠
Step 2 PR 입니다! ㅎㅎ
- `BankError` 타입 구현
- `Client`
- `Rating` : 고객등급의 종류를 나열한 열거형
- `create()` : 고객을 생성하여 Client 배열을 반환해주는 메소드
(원래는 Bank 타입에 있었지만 Client로 옮김)
- `getTask()` : task 프로퍼티를 반환해주는 메소드
(task 프로퍼티를 숨기고 이 메소드를 통해서 task 프로퍼티를 가져올 수 있도록 함)
- `BankTaskOperation`
- `TaskType` : 업무 종류를 나열한 열거형
- `createTask()` : 업무를 랜덤으로 생성해서 반환해주는 메소드
- `getTaskTime()` : taskTime 프로퍼티를 반환해주는 메소드
- `getClientRating()` : clientRating 프로퍼티를 반환해주는 메소드
- `BankManager`
- `handleTask()` : `assignTaskPriority()` 를 호출하여 업무 우선순위를 할당해준 후 우선순위대로 업무를 처리하고 `calculateTaskTime()`을 호출하여 총 업무시간을 반환해주는 메소드
- `assignTaskPriority()` : 고객 등급에 따라 업무 우선순위를 할당해주는 메소드
- `calculateTaskTime()` : 총 업무 시간을 계산해서 반환해주는 메소드
- `main`
- 메뉴 선택에 따른 실행문 구현
1. `Client라는 객체에서 캡슐화를 통해 프로퍼티들을 다 숨기고 원하는 일을 해서 원하는 데이터를 …
=> [Step2] Hailey, Henry

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/QueueTest/Info.plist, BankManagerConsoleApp/QueueTest/QueueTest.swift
@TaeJoongYoon 
안녕하세요 타일러!!! 저희 step1을 완성시켜서 PR 보냅니다~
잘부탁드려요 :)
---
1. LinkedList를 이용하여 Queue 타입 구현
2. Queue 클래스내 메서드 테스트 코드 작성
---
1. Queue 클래스 메서드에서 구현해 놓은 LinkedList내 메서드를 호출하는 부분이 대부분입니다. 이러한 경우 따로 타입을 빼서 Queue를 구현하는 것이 맞는지 궁금합니다. 저희는 LinkedList 이용한 Queue 자료구조를 외부에서 사용하기 때문에 따로 타입을 빼서 구현했습니다.
2. 이번 프로젝트에서 콘솔앱과 ui앱 프로젝트가 따로 존재하는데 BankManager 파일이 연동이 되는것을 보았습니다. xcode에서 프로잭트 파일 관리가 전반적으로 어떻게 되는지 궁금합니다.
=> 은행 창구 매니저 [Step1] 샤피로, 산체스

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleAppTests.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Node.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift, BankManagerConsoleApp/BankManagerConsoleAppTests/Info.plist
@SungPyo 
@KimWanki @keeplo
안녕하세요 웨더!! 🤠
이번 프로젝트 함께 하게된 루얀, 말꼬입니다 
웨더는 요즘 더운 날씨 잘보내고 계신가요 좀 덥긴 하지만 맑은 날씨가 많은데 
항상 웨더도 맑은 날씨처럼 기분이 좋으시길 응원합니다!!
이번엔 자료구조 Linked List와 리스트로 구현한 Queue를 구현해보고 
각 매서드의 검증을 UnitTest를 통해 진행 해보았습니다
테스트 작성에 고민을 많이 해보았습니다... 디테일한 피드백 부탁드립니다!! 
* **Node 타입의 저장 프로퍼티 접근자 관련**
~~~swift
final class Node<T> {
var value: T
var next: Node?
init(value: T, next: Node?) {
self.value = value
self.next = next
}
}
~~~
저희 생각에 사용자 타입의 저장 프로퍼티는 기본적으로 `private` 연산자를 쓰는 데
현재는 접근 수준을 높이지 않고 default로 만들어 보았습니다. 
단순히 값을 저장하는 도구로써 사용되어서 직접 접근하게 구현해보았는 데
이대로 구현하는 것도 괜찮을 지 간접 접근 방법으로 다르게 구현하는게 좋을지 궁금합니다 
* **tail ? strong ? 그것이 문제로다**
~~~swift
// tail의 참조 카운팅 : 1
/*
tail을 strong으로 선언하면, clear() 내부에서 명시적으로 tail이 nil이 되는 시점을 결정
참조 해제 시점을 결정할 수 있기 때문에 메모리 해제 시점을 알 수 있다.
*/
private var head: …
=> [STEP 1] Luyan, Marco

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/QueueTests.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp/CustomCollections/Node.swift, BankManagerConsoleApp/BankManagerConsoleApp/CustomCollections/Queue.swift, BankManagerConsoleApp/QueueTests/Info.plist, BankManagerConsoleApp/QueueTests/QueueTests.swift
안녕하세요 @wonhee009  
저희 Step1 진행하고 PR보냅니다. 잘 부탁드립니다.🙏🏻
1. 참조 카운트 관련
```swift 
func clear() {
head = nil
tail = nil
}
// head -> node -> node -> node <- tail
//          (1)     (1)    (2)
// head = nil 인 경우
// head -> | node -> node -> node <- tail
//            (0)     (1)    (2)
// head -> | node -> | node -> node <- tail
//            (0)       (0)    (2)
// head -> | node -> | node -> | node <- tail
//            (0)       (0)      (1)
// tail = nil 인경우
// head -> | node -> | node -> | node | <- tail
//            (0)       (0)      (0)
clear() 에서 head 와 tail 에 nil 을 할당하면,
위와 같은 과정으로 참조카운트가 결국 0이 될 거라 추측을 하였는데, 이 생각이 맞는지 확인 받고싶습니다!
```
2. 함수, 연산 프로퍼티 선택 기준
- 함수와 연산 프로퍼티를 선택할 때 값을 리턴하지 않는 형태의 함수를 읽기 전용 연산 프로퍼티로 만들거나, 함수 파라미터가 없을 경우 함수를 연산프로퍼티로 만들 수 있다고 알고 있는데요. 이와 관련해서 라쟈냐의 선택 기준이 궁금합니다. …
=> [Step1] Jost, Hosinging 

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/LinkedListTests/Info.plist, BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift, BankManagerConsoleApp/QueueTests/Info.plist, BankManagerConsoleApp/QueueTests/QueueTests.swift
@1Consumption 
안녕하세요 올라프 ! STEP1이 완성되어 첫번째 PR을 보냅니다! 잘부탁드립니다.🙇
---
- 연결리스트를 이용한 큐 타입을 구현할 때 구조체와 클래스 중 어떤 것을 사용해야할지 아직 잘 모르겠습니다.
mutating이 사용될때마다 인스턴스를 다시생성한다는 의견이 있어서 질문드립니다.
- 큐는 데이터의 입력과 출력 방향이 고정되어있기에 doubly보다는 singly로 짜는게 더 좋다고 생각하였고 singly에 tail을 만들어 준 이유는 addLast를 할 때 head만 있는 경우는 시간복잡도가 O(n)이지만 tail이 있다면 O(1)이기에 좀 더 이점이 있다고 생각하였습니다. 그런데 조금 의문인거는 단순히 하나의 메소드를 위해서 tail이라는 노드를 만들어 주는게 맞는지 올라프의 생각이 궁금합니다.
- LinkedList.swift 50번째라인을 하면 head랑tail을 같은 곳을 가리키게 되어 문제가 생길꺼라고 생각했는데 잘 돌아갑니다. 왜그럴까요?
- 더 다양한 방법이 있을 것 같은데 저희가 구현한 방법 이외에 어떤 것들을 더 테스트해볼수 있을까요?
=> 은행 창구 매니저 [STEP 1] 잼킹, yun, 승기

BankManagerConsoleApp/BankManagerConsolAppTest/BankManagerConsolAppTest.swift, BankManagerConsoleApp/BankManagerConsolAppTest/Info.plist, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/BankManagerQueue.swift, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Node.swift, README.md
@leejun6694 
안녕하세요!!쿠마 저희 step1을 진행완료되서 PR을 보냅니다~
부족하지만 잘 부탁드려요 :)
---
1. Node 생성하는 클래스 작성  
2. Node을 통하여 LinkedList 구현
3. LinkedList를 이용하여 Queue타입 구현
---
1. BankManagerQueue가 class여야 되는지 구조체 여야되는지 잘 모르겠습니다. 상속이나,참조할 이유가 없으면 구조체로 선언하면 된다고 알고 있어서 구조체로 진행하였는데요. 
구조체 내부 프로퍼티에 클래스 타입이 있을때,참조 오버헤드?? 이런게 발생해서 성능에 안좋다고 봐서 어떤 타입으로 선언해야되는지 감이 안잡힙니다.혹시 깊은 복사와 얕은 복사와 관련된건지 잘 모르겠습니다ㅠㅜ
2. LinkedList에서 removeFirst()와 peekFirst() 의 리턴값이 Node를 반환하고 있습니다.노드를 반환하는게 좋은건지 아니면 노드의 데이터를 반환해주는게 좋을지 잘 모르겠습니다.
3. 마지막은 저희가 대화방에 말해드린 내용인데요.참조 카운트 관련해서 removeFirst()시 다음 Node의 링크를 가르킬떄 기존 Node는 참조카운트가 없어져 자동으로 소멸되는게 맞을까요?? 이러한 관점에서 removeAll()도 head에 nil을 입력하면 연달아서 node의 참조 카운트가 다 없어지게 되는게 맞는건지 궁금합니다.
=> [Step1] 지스,건 

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
@SungPyo
@KimWanki @Keeplo
안녕하세요 웨더!! 🤠🤠🤠
스텝2를 보냅니다. 벌써 한 주가 또 지나갔네요! 한 주간 고생 많으셨습니다.
지난 번에 회의실 오셔서 편하게 많은 얘기해주셔서, 정말 감사했습니다. ( 또 와주세요! )
스텝2의 요구사항이 엄청 많진 않았다고 생각합니다. 아마 스텝3에서 많은 내용을 질문을 하게 되지 않을까 생각합니다.
업무에 대한 처리 시간을 `bankManager` 이 가지고 있는게 좋을지, `Customer` 이 가지고 있을지 고민했는데,
기능 상세에서 은행원이 업무를 처리한다는 관점에서 `bankManager` 이 가지고 있으면 좋겠다고 생각해서 은행원의 프로퍼티로 선언했습니다.
현재 코드에서는 Bank 타입이 `private var customerQueue: Queue<Customer>`을 가지고 있는데요. 은행에 고객이 없을 수도 있다라는 관점에서 봤을 때, 또 은행이 고객을 포함하진 않는다.라 생각에서 `bank.open()` 메서드의 파라미터로 받는게 더 맞는 구조가 아닐까 생각했습니다. 이렇게 했을 때 메모리 측면에서도 효율적이라고 생각하는데, PR에는 반영을 하진 않았지만, 하단의 코드 내용으로 변경을 하는건 어떻게 생각하시는지 궁금합니다.
```
struct Bank {
private var manager: BankManager = BankManager()
private var customerCount: Int = 0
private var totalTime: Double = 0
mutating func open(_ customerQueue: …
```
=> 은행창구 매니저 [Step2] Luyan, Marco

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/test2.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankTeller.swift, BankManagerConsoleApp/BankManagerConsoleApp/Client.swift, BankManagerConsoleApp/BankManagerConsoleApp/CustomCollections/Node.swift, BankManagerConsoleApp/BankManagerConsoleApp/CustomCollections/Queue.swift, BankManagerConsoleApp/BankManagerConsoleApp/QueueTicketMachine.swift, BankManagerConsoleApp/BankManagerConsoleApp/TaskCategory.swift, BankManagerConsoleApp/BankManagerConsoleApp/Utils/BankManagerErrorMessage.swift, BankManagerConsoleApp/BankManagerConsoleApp/Utils/Namespace.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/QueueTests/QueueTests.swift
안녕하세요 라쟈냐 @wonhee009 
먼저, 늦은 시간에 PR보내게되서 죄송합니다. 주말에 리뷰를 받고 싶다기보다 월요일에 학습활동도 있고, 팀원 모두가 오전에 스케쥴이 있어서 보낼 시간이 애매할 것 같아서 지금 보내게됐습니다. 양해부탁드립니다.
---
> TypeAlias를 Bank, BankManage 타입 내부에 있는 메서드의 리턴 타입으로 사용을 하기 때문에 의존 관계로 표현을 해봤는데 TypeAlias는 사용자 정의 타입이 아닌데 의존으로 보는게 맞을지 궁금합니다.
> UML 관련, Generic 타입이 매개변수와 리턴타입으로 사용되는경우, 이들과 연관관계로 표현을 하는 것이 맞느지 궁금합니다.
> Mark주석을 활용해 봤는데 작성하다보니 과하게 작성이 된 것 같은 느낌이 있는데 라자냐의 사내에서는 Mark주석에 대한 어떤 Convention을 가지고 있는지 궁금합니다.
> OOP설계 관련해서 역할과 기능 상세에 따라 타입 내 프로퍼티와 메서드를 타입의 역할에 맞게 만들려고 노력을 했습니다. 근데, 이 부분 관련해서 적절하게 설계가 된 것인지 의견부탁드립니다.
=> ios-bank-manager[Step2]Jost, Hosinging

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift, BankManagerConsoleApp/BankManagerConsoleAppTests/Info.plist
@hyunable 
혀나블 안녕하세요!
늦었지만 Step1 PR을 보내봅니다 ☺️
잘 부탁드립니다! 🙏
어떤 방식으로 dummyNode를 만들어야할지 잘 모르겠어서 현재와 같은 방법으로 구현했습니다. 혹시 이에 관해 조언을 구할 수 있을까요? 🤩
class를 참조할 때는 struct가 class를 참조하게 하는 것보다 class가 class를 참조하게 하는 것이 좋다는 이야기를 들어서 LinkedList와 Queue를 모두 class로 구현했습니다.
하지만 struct의 복사가 많이 일어나지 않는다면 reference counting 오버헤드가 크지 않아 class가 아닌 struct로 구현해도 문제가 없다는 생각이 들었는데 어느 방식이 나은지 궁금합니다! 🤩
Unit Test에서 마지막 테스트처럼 given에 아무런 값을 선언하지 않아도 괜찮은지 궁금합니다
=> [Step1] Coden, Joey

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift, BankManagerConsoleApp/Tests/QueueTestDouble.swift, BankManagerConsoleApp/Tests/Tests.swift
안녕하세요 쿠마!! @leejun6694 
은행 창구 매니저 Step1 PR 작성하여 보내드립니다.😄
잘부탁드립니다!🙏 
Queue 타입을 만들고 유닛테스트 코드 작성을 하며 '어떤 기능까지 테스트할지', '테스트 케이스는 무엇을 할지'가 고민이었습니다. 저희는 메서드단위로 적당한? 테스트케이스를 선정하게 되었는데 쿠마는 어떤 기준으로 테스트할 기능과 테스트 케이스를 선정하시는지 궁금합니다
Queue가 비었는지 테스트 하기 곤란했어요. head와 tail이 private 프로퍼티라서, isEmpty 프로퍼티를 테스트 코드에 사용했어요.
그리고 private 프로퍼티에 접근할 수 있는 모델을 테스트용으로 따로 만드는건 어떤가요? 코드를 복사해서 internal로 바꿔서 쓰는것도 생각했어요. 이래도 될까요?
```swift
// 아래 코드를 Tests에 넣기
struct QueueTest<T> {
var head: Node<T>?
weak var tail: Node<T>?
...
}
```
Development Target을 10.15버전으로 설정 하고 프로젝트를 진행하였는데 아래와 같이 최소 macOS 11.0버전 이상을 사용해야한다는 에러가 발생하였습니다.
> <unknown>:0: error: compiling for macOS 10.15, but module 'BankManagerConsoleApp' has a minimum deployment target of macOS 11.0: /Users/bagbyeongho/Library/Developer/Xcode/DerivedData/BankManagerCon …
=> 은행 창구 매니저 [STEP1] 요한, aCafela coffee, 호박

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerTests.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/BankManagerTests/CustomQueueTest.swift, BankManagerConsoleApp/BankManagerTests/CustomerQueueTest.swift, BankManagerConsoleApp/Error/LinkedListError.swift, BankManagerConsoleApp/Model/CustomerQueue.swift, BankManagerConsoleApp/Model/LinkedList.swift
안녕하세요 그린 !!!! @GREENOVER 
앞으로 2주간 잘 부탁드립니다 :) 
저번 계산기 프로젝트에서 구현해본 `LinkedList`지만 다시 해보니 서툰 부분 투성이네요. 부족한 점이 많지만 잘 부탁드립니다.
- 은행에 도착한 고객이 임시로 대기할 대기열 (Queue) 타입을 구현하는 것이 목표였습니다.
- 먼저 Linked-list 타입을 구현하고, 이를 활용하여 Queue 타입을 구현했습니다. 그리고 Queue 타입에 대해 Unit Test를 작성했습니다. 
1.1 그린이 짚어주셔서 프로젝트 요구사항에서 Queue를 구현할 때 왜 성능이 좋은 `Double Stack Queue`가 아니라 `Linked-list`를 활용하라고 했을지 고민했습니다.  
먼저 `Linked-list`의 특징을 배열과 비교해봤습니다.
||배열|Linked-list|
|---|---|---|
|장점|임의 접근이 가능|임의의 요소 추가/삭제가 쉬움|
|단점|맨 앞의 요소를 제거하면 모든 요소 위치를 옮겨줘야 해서 비효율적 (시간복잡도 O(n))|임의 접근이 불가하고, head부터 찾아야 함|
그리고 `Double Stack Queue`는 배열을 뒤집는 메서드 `reversed()`의 시간복잡도가 O(1) 이므로 Queue로 활용했을 때 큰 장점이 있다고 알고 있습니다.
STEP2/3의 내용을 미리 알 수 없어서 추측해보았는데, `은행창구의 손님 대기열`이므로 중간에 줄 서서 기다리다가 나가는 손님이 발생하는 상황 등 Queue의 중간에 값을 추가/삭제하는 기능이 필요하여 `Linked-list`를 사용할 것으로 …
=> 은행 창구 매니저 [STEP1] July, 애플사이다

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/QueueTest/QueueTest.swift
@protocorn93 
@Kim-EunsooSilver
안녕하세요 콘! 
저희 스텝1 PR 제출합니다!
진행하면서 고민했던 부분들 위주로 정리해서 적었습니다.
이번 프로젝트, 이번 리뷰 잘부탁드립니다 😊
---
- 상수, 변수명에 대한 고민
- 처음 작성 시에는 향후에 다른 메서드들에서 구현될 value라는 이름을 가진 프로퍼티와의 구분을 위해서 nodeValue라고 작성하고 호출시에는 value란 전달인자명이 보이지 않도록 하려고 했습니다. 하지만 타입명과 프로퍼티명이 겹치는 네이밍을 피하기 위해 value로 변경하여 작성했습니다.
```swift
<기존>
class Node<Element> {
let nodeValue: Element
var next: Node?
init(_ nodeValue: Element, next: Node? = nil) {
self.nodeValue = nodeValue
self.next = next
}
}
<변경>
class Node<Element> {
let value: Element
var next: Node?
init(value: Element, next: Node? = nil) {
self.value = value
self.next = next
}
}
```
- 연결리스트의 포인터라는 의미로 pointer로 네이밍을 고민하다가 보다 직관적으로 이해하기 쉽기 위해 next로 결정했습니다.
- 연결리스트에 임의로 접근해 데이터를 변경할 수 있는 가능성을 방지하고자 LinkedList 타입에 접근제어를 추가했습니다. 다만, 변경만 불가능하고 읽기는 가능하도록 …
=> 은행 창구 매니저 [STEP 1] nicholas, 호랭이

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/BankDelegate.swift, BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift, BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift, BankManagerConsoleApp/BankManagerConsoleApp/Model/ConsoleBundle.swift, BankManagerConsoleApp/BankManagerConsoleApp/Utility/NumberFormatter+Extension.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, README.md
안녕하세요 그린😊 @GREENOVER 
스텝2 마무리하여 PR요청드립니다. 
구조 설계를 고민하느라 진행이 좀 늦어졌습니다🥲
설계에 대한 피드백 아낌없이...주시면 감사하겠습니다! 
이번 스텝도 잘 부탁드립니다🙇🏻‍♀️🙇🏻‍♂️
<br>
**1. BankManager의 역할**
이번 프로젝트는 같은 코드를 공유하는 Console App과 UI App 2개를 만들기 때문에, BankManager는 양쪽에서 모두 쓰일 수 있게 공통적인 기능만 담고 있어야 된다고 생각했습니다. 처음에는 `BankManager`가 main에서 직접 사용되면서 Console App의 실행을 담당 했는데요, `ConsoleManager`라는 별도의 타입을 만들어 Console App의 실행은 전적으로 해당 타입에서 담당하는 것으로 리팩토링 하였습니다. 또한, `ConsoleBundle` name space에서 Console App에서 쓰이는 String을 관리하도록 하여 공통으로 쓰이는 코드에서는 해당 String들을 직접적으로 알지 못하게 하려 했습니다. 다만, 이번 스텝에서는 `Bank`타입과 `BankClerk` 타입에서 `ConsoleBundle`를 직접 사용하는것을 수정하지는 못했습니다.  
<br>
**2. Bank인스턴스 초기화 시점에 대한 고민**
`ConsoleManager`의 `run()` 안에서 
- 1) case가 은행개점일 때 마다 Bank인스턴스를 생성해줄 지
- 2) while구문 전에 Bank인스턴스를 초기화 한 후, 일처리를 한 뒤 인스턴스의 프로퍼티를 초기화해준 후 인스턴스를 재 사용할 지 …
=> 은행 창구 매니저 [STEP 2] 릴리, 숲재

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
@yohanBlessYou @hoBahk
안녕하세요 쿠마! @leejun6694
잘 부탁드립니다.
예금업무는 동시에 2명까지, 대출업무는 1명이 업무를 처리해야 합니다. 이를 위해  Concurrent Queue에 DispatchSemaphore를 설정하는 구조로 구현하였습니다. 이후 세마포어를 기다리는 작업을 Main Thread에게 시키면 App이 멈추므로 업무별 Serial Queue를 만들어주고 거기서 기다리도록 구현하였습니다.
현재 저희의 로직은 예금업무 고객와 대출업무 고객을 두개의 시리얼큐를 만들어 각 큐에 넣어주고 시리얼 큐 안에서 글로벌큐를 만들고 세마포어로 쓰레드 수를 제어하고있습니다.
그런데 코드가 너무 길어져 함수를 분리하는 과정에서  아래 코드 중 `processDepositService` 메서드와 `processLoanService`메서드 안에서 `async()` 메서드를 사용합니다. 그래서 한눈에 로직을 파악하는 것이 어렵다고 보였습니다.
`DispatchWorkItem` 을 사용해보려고 했으나 `while`문 안에서만 사용할 수 있는 `client` 상수를 사용할 수 없었습니다.
이런 상황에서 메서드 안에 `async()` 메서드를 사용하고 있다는 것을 쉽기 알리기 위해서 저희가 생각한 방법은 메서드명으로 알리기, 주석으로 알려주기 아니면 애초에 이런 로직은 함수로 분리하지 않는다? 등 생각을 해보았습니다.
이런 상황일 때 쿠마는 어떻게 하시는지 궁금합니다! 🤔
```swift
while let client = clients.dequeue() {
switch …
```
=> 은행 창구 매니저 [STEP3] 요한, aCafela coffee, 호박

.gitignore, .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata, BankManager.swift, BankManagerConsoleApp/.swiftlint.yml, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/QueueTest.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/contents.xcworkspacedata, BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Node.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/Podfile, BankManagerConsoleApp/Podfile.lock, BankManagerConsoleApp/QueueTest/QueueTest.swift, README.md
안녕하세요 올라프!  @1Consumption 
Step1 첫번째 PR입니다! 잘부탁드립니다🙇‍♀️
-------
- 클래스와 구조체를 선택할 때 여러 기준이 있지만 어떤 데이터를 포함하고 저장소의 역할을 한다면 클래스를, 틀의 기능을 한다면 구조체를 선택할 것 같습니다. Node와 Linked List는 자료구조의 역할을 하기 때문에 클래스로, CustomerQueue는 Linked List를 포함하고 이를 활용하는 특수한 큐라고 생각되어 구조체로 구현하였습니다.
- symbol을 찾을 수 없다는 내용의 오류가 발생해서 구글링해보니, Targets-Build Phases-Compile Sources에서 Test에서 사용할 함수가 포함된 파일이 리스트에 있는지 확인하고 추가를 해야한다는 내용이 있었습니다. 실제로 QueueTest 타겟의 Compile Sources에 QueueTest.swift 자기자신의 파일만 있어서, 테스트에 필요한 다른 파일들도 추가해주었더니 정상적으로 테스트가 실행되었습니다.
- swiftlint 라이브러리를 이번 프로젝트에 포함시켜서, main.swift 파일에 swiftlint의 내용을 테스트하기 위한 코드만 작성을 했었습니다. 테스트를 해보고 나서 main.swift 파일을 삭제했는데 오류가 발생했었습니다. 그 이유를 찾아보니 프로그램은 Entry Point(프로그램의 시작 지점)을 찾아 그 곳에서부터 시작하고 애플 공식 문서에서는 `the main attribute, the NSApplicationMain attribute, the UIApplicationMain …
=> 은행 창구 매니저 [STEP 1] grumpy, marisol

.gitignore, BankManager.swift, BankManagerConsoleApp/.swiftlint.yml, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/contents.xcworkspacedata, BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/Model/LinkedList.swift, BankManagerConsoleApp/Model/Node.swift, BankManagerConsoleApp/Model/Queue.swift, BankManagerConsoleApp/Podfile, BankManagerConsoleApp/Podfile.lock, BankManagerConsoleApp/QueueTest/QueueTest.swift
@yoo-kie
안녕하세요 개굴! 이번 PR도 잘 부탁드립니다!
(https://hackmd.io/5FB3nnO3TFKVKGunXiwRwA)
우롱차: 어차피 외부에서 함수로 변경 및 값을 볼 수 있는대 Private으로 하는게 무의미하다.
민성: 외부에서는 함수로만 Node의 상태를 알고 변경할 수 있는게 맞다고 생각한다.
객체지향에서는 객체의 자율성을 위해 캡슐화 하는 것이 좋다고 생각
```swift=
//우롱차의 방법
final class Node<T> {
private(set) var element: T
var nextNode: Node?
init(element: T, nextNode: Node? = nil) {
self.element = element
self.nextNode = nextNode
}
}
```
```swift=
//민성의 방법
final class Node<T> {
private var element: T
private var nextNode: Node?
init(element: T, nextNode: Node? = nil) {
self.element = element
self.nextNode = nextNode
}
func data() -> T {
return element
}
func setNextNode(_ nextNode: Node) {
self.nextNode = nextNode
}
func next() -> Node? {
return nextNode
}
}
```
call by value, call by reference 했을때 문제가 일어나는의 여부
구조체와 클래스의 …
=> 은행 창구 매니저 [STEP1] 우롱차, 민성

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Model/BankCustomer.swift, BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift, BankManagerConsoleApp/BankManagerConsoleApp/Model/Banking.swift, README.md
안녕하세요 @TTOzzi  STEP3 PR보냅니다.
STEP2의 추가적인 수정사항과 STEP3 새로운 기능을 구현했습니다.
기본적인 부분(protocol extension으로 분리, 접근제어자, final 키워드)을 자꾸 놓치는것 같아 해당 부분에 신경을 더 써봤습니다
약간의 문제가 있습니다..
STEP2 수정사항도 STEP3 Branch에서 한다음 PR을 했어야 했는데, STEP2에서 작성하고, 새 기능들만 STEP3에서 작성해 버려서 리뷰하시기 불편할것 같아요.. ㅠㅠ 죄송합니다
잘부탁드립니다 :)
프로토콜에 AnyObject를 채택해서 weak으로 선언할 수 있게 해줬습니다!
```swift
weak var delegate: BankDelegate?
```
수정하는 중에 의문이 하나 들었는데요!
weak을 쓰려면 무조건 프로토콜에 AnyObject를 채택해줘야 하는데 그러면 앞으로 구조체에는 해당 프로토콜 채택을 못하지 않나..? 라는 생각이 들었어요
다시 생각을 해봤는데, 어차피 UIKit에서는 대부분 Delegate의 주체들이 ViewController다 보니 상관없을것 같다는 생각이 들었습니다
```swift
private lazy var bank: Bank = {
var bankWindow = BankCommonWindow()
bankWindow.delegate = self
let bank = Bank(window: bankWindow)
bank.delegate = self
return bank
}()
```
BankManager에서 bankWindow 프로퍼티를 가진다는게 논리적으로 조금 …
=> 은행 창구 매니저 [STEP3] Eddy, dudu

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/Model/Bank/Bank.swift, BankManagerConsoleApp/Model/Bank/BankClerk.swift, BankManagerConsoleApp/Model/Bank/Client.swift, BankManagerConsoleApp/Model/Bank/DepositBankClerk.swift, BankManagerConsoleApp/Model/Bank/LoanBankClerk.swift, BankManagerConsoleApp/Model/Bank/TaskType.swift, BankManagerConsoleApp/Model/Bank/Timer.swift, BankManagerConsoleApp/Model/Bank/WorkType.swift
@yoo-kie
안녕하세요 개굴! 이번 PR도 잘 부탁드립니다!
1. 은행원의 종류가(예금, 대출)로 나뉘는 것을 어떻게 구현해야 할 지 고민하였다.
-> 은행원의 공통된 기능을 extension protocol로 구현해주었고 예금, 대출은행원이 은행원 프로토콜을 채택함으로써 해결하였다. 
2. 캡슐화가 잘되있다보니 객체간 의사소통하는 일이 별로 없다. 이 때문에 테스트 코드를 구현하기 힘들다.
3. startWork 내부에서 case로 묶은 부분의 코드가 깔끔하진 않은거 같다. 오버로딩으로 바꿔볼까 했지만 오히려 그편이 더 복잡해지는거 같아서 그만두었다.
4. updateWorkData 부분을 비동기로 실행하여 race condition이 발생하지 않을까 싶었는대. 동시에 실행하는 쓰래드수가 1,2명일때는 티가 안나지만 100,100 과 같이 동시에 실행하는 쓰래드 수를 늘리니 숫자가 안맞는 문제가 발생하였다.
-> 시리얼 큐를 만들어 업데이트 하는것은 거기서 하도록 변경하였다.
5. 은행업무가 전부 끝나지 않았는데 은행의 하루 일과를 출력하는 print가 실행되는 문제가 발생되었다.
-> DispatchGroup으로 작업들을 묶어주어 작업이 끝나는 시점에 print를 하도록 해결하였다.
1. 프로토콜에 weak var 로 선언하려 했으나 알수 없는 경고들이 많이 떳다. 알고보니 class에서만 사용 가능했다! 그래서 사용하는 프로토콜을 AnyObjcet로 변경하였다.
2. DispatchSemaphore에 대한 개념이 매우매우 햇갈렸다. 처음에는 스레드의 제한숫자라고 이해했으나. 나중에 다시읽어보니 접근 …
=> 은행 창구 매니저 [STEP3] 우롱차, Minseong

BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankClerk.swift, BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/Customer.swift
@Monsteel 
안녕하세요!토니! STEP3 완료해서 PR보냅니다!
잘부탁드립니다!😁😄
생성되는 은행원마다 식별자가 있다면(ex이름, 직책 등등) 은행원 하나하나를 인스턴스로 생성하는게 맞다고 생각합니다
다만, 지금 프로젝트에서는 은행원마다 식별자가 없고 은행원의 수는 semaphore의 value값으로 대체할 수 있기 때문에 인스턴스 생성은 단순 메모리 낭비라고 생각해 따로 생성하지 않았습니다
위와 같은 이유로 인스턴스를 생성할 필요가 없다고 판단된 BankClerk은 enum으로 구현하였습니다
mutating 함수 내에서 async 호출 시 위와 같은 오류 발생 했습니다
근데 sync 호출 시 문제가 발생하지 않았습니다
위 내용으로 미루어 보았을 때 sync로 선언되면 해당 쓰레드에서 일하는 동안 다른 스레드는 block될 것이고 그 동안 클로저가 보고있는 구조체의 값들은 이 클로저에서 바꾸지 않는 이상 바뀔 여지가 없어서 오류가 발생하지 않는 것이라고 생각했습니다
반면, async의 경우 escaping클로저로 해당 메서드가 진행되면서 다른 쓰레드의 일도 처리가 되기 때문에 그 과정에서 원래 값이 바뀌는 등 문제가 발생할 수 있다고 생각했습니다
(예를 들면, 사용하려는 프로퍼티가 async진행중에 nil이된다거나 메모리에서 없어진다거나 하면 오류가 발생되는 문제)
그래서 다른 쓰레드로 escaping을 시킬 때 그 당시의 self를 캡쳐해서 보내면 문제가 해결이 되었습니다
그런데 mutating 메서드 내에서 어떤 값 변경 없이 단지 접근만 하는 경우에도 위 문제가 발생 되었습니다.
그래서 아래와 …
=> 은행 창구 매니저 [STEP3] 쿼카, 두기

BankManagerUIApp/BankManagerUIApp.xcodeproj/project.pbxproj, BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift, BankManagerUIApp/BankManagerUIApp/Base.lproj/Main.storyboard, BankManagerUIApp/BankManagerUIApp/Model/Bank.swift, BankManagerUIApp/BankManagerUIApp/Model/BankManager.swift, BankManagerUIApp/BankManagerUIApp/Model/BankingTask.swift, BankManagerUIApp/BankManagerUIApp/Model/BankingTimer.swift, BankManagerUIApp/BankManagerUIApp/Model/Teller.swift, BankManagerUIApp/BankManagerUIApp/ViewController.swift, README.md
안녕하세요 올라프!⛄️ @1Consumption 
우선 지난 2주동안 정말 감사했습니다🤲🤲
여러모로 많은 도움을 주셨고, 저희 또한 많은 것을 얻어간 것 같아 굉장히 뿌듯합니다!
마지막으로 step4 PR 보냅니다! 
고민한점과 프로젝트를 진행하면서 궁금했던 점들, 작성해보았습니다
잘부탁드립니다~ 🙇‍♂️🙇‍♀️
___
- 고객을 대기중에 보내고, 업무중에 보내고, 업무중에서 제거하기 위해 `CustomerSendable` Protocol을 생성했습니다. stackView의 subview들인 Label들을 배열로 받고, 배열을 돌면서 대기중에 있는 label의 text와 일치하면 removeFromSuperView를 해주는 방식으로 대기중에 있는 고객을 삭제하고 업무중에 새로 라벨을 추가해주었습니다. 업무중에 있는 고객을 제거할 때도 동일한 방법으로 했습니다.
- 프로젝트 문서의 내용은 다음과 같습니다.
> 초기화 버튼을 누르면 대기중인 고객과 타이머 모두 초기화됩니다.
저희는 이 중에서 대기 중인 고객을 초기화하는 방법이 쉽게 떠오르지 않아 많은 고민을 했습니다. 결국 뷰 컨트롤러에서 `bankManager`를 통해 직접 구현했던 큐의 `clear`기능을 호출하는 방법으로 구현했는데요, 이 기능을 위해 `private`하지 않은 추가적인 메서드가 생성된다는 게 너무 아쉬운 부분입니다.  
- Console App에서 구현한 Model를 UIApp의 ViewController에 어떻게 연결할지 고민했습니다. Notification Center과 Delegate Pattern을 생각해봤는데요, …
=> 은행 창구 매니저 [STEP 4] grumpy, marisol

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/CustomerQueueTests.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Node.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/CustomerQueueTests/CustomerQueueTests.swift
안녕하세요 제이슨! @ehgud0670 😆
은행 창구 매니저 프로젝트를 진행하게 된 재재와 나이든별입니다.
Step 1 리뷰 잘 부탁드리겠습니다!
> 프로젝트 기간 2022.06.27 월  ~ 2022.06.28 화 </br>
팀원: 재재, 나이든별</br>
리뷰어: 제이슨
---
[![swift](https://img.shields.io/badge/swift-5.6-orange)]()
[![xcode](https://img.shields.io/badge/Xcode-13.3-blue)]()
1. **프로토콜 Queue 구현**
- 여러가지 자료구조로 구현이 가능하기 떄문에 Queue가 준수하는 사항을 먼저 명세해주면 좋을 것 같다고 생각하여 protocol로 구현을 해주었습니다.
2. **Node 구현**
- Node는 연결리스트의 구조 상 Node는 next property가 다음 Node를 참조하기 때문에 클래스가 적절하다고 생각하여 구현해주었습니다.
3. **LinkedList 구현**
- Queue에 필요한 필수적인 기능만 구현을 해주었습니다. 
4. **CustomerQueue 구현**
- Queue 프로토콜을 채택하고, linkedList 타입 메서드를 통해 Queue에 필요한 기능을 구현해주었습니다. 
5. **CustomerQueueTest 실패**
- CustomerQueueTest 를 생성하였지만 실패하여 고민중에 있습니다.
>CustomerQueueTest 파일을 생성한 후 `@testable import` 의 모듈을 찾지 못하는 에러에 대해서 서치해보고 해결하려고 하였으나, 나별 …
=> 은행 창구 매니저 [STEP1] 재재, 나별

BankManagerConsoleApp/.swiftlint.yml, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/QueueTests.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankerLogic.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Node.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/BankManagerConsoleApp/QueueError.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/QueueTests/QueueTests.swift, README.md
안녕하세요 @protocorn93 🌽 @apwierk2451  와 @Judy-999 입니다 🤗
STEP 2 PR 보내드립니다 !! 🫡
이번에도 잘 부탁드립니다 !! 😁😁
코드의 이해를 돕고자 UML도 첨부합니다!
고객, 은행은 요구사항에 있는 타입이고 추가적으로 **Banker**와 **BankManager** 타입을 구현했습니다. 
> 업무를 보는 주체인 은행원 구조체
`serve(customer: Customer)`: 고객을 상대로 업무를 처리하는 메서드
> 은행의 일을 관리하는 관리자(=BankManager) 구조체
`openUpBank`: 은행 개점 여부를 묻는 메서드
`selectWork(_ status: String)`: 은행 개점 여부를 선택하는 메서드
`startBanking`: 업무 시작을 지시하는 메서드
> 은행 구조체 
`banker`: 은행에 있는 은행원을 나타내는 프로퍼티
`customer`: 은행에 온 고객들의 대기열을 나타내는 프로퍼티
<br>
**Queue**에서 `dequeue`를 실행했을 때 큐가 비어있어 값을 꺼낼 수 없으면 `nilOfValue` 에러를 던지도록 했습니다. 그렇기 때문에 **BankManager**에서 업무를 처리하는 `startBanking` 메서드에서 고객 대기열에서 한 명씩 `dequeue`할 때 에러처리가 필요했습니다.
모든 고객의 업무를 보기위해 큐의 `isEmpty`가 `true`일 때까지 `dequeue`를 반복하도록 해주었는데 While 반복문과 do-catch 에러처리 순서에 대해 고민했습니다.
```swift
// 첫 번째 방식: do …
```
=> 은행 창구 매니저 [STEP2] Judy, bonf

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/Bank/Banker.swift, BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/Enum/BankWorkType.swift, BankManagerConsoleApp/BankManagerConsoleApp/Enum/ProcessingTime.swift, BankManagerConsoleApp/BankManagerConsoleApp/Enum/WorkType.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
안녕하세요~!! @corykim0829 😁
많이 어려웠던 STEP3 PR 보냅니다 !!
부족하지만 잘 부탁드리겠습니다~!! 감사합니다!
프로젝트에서 요구하는 은행의 역할이 현실세계의 은행과 조금 다른점이 있습니다.
해당 Bank클래스의 역할은 BankManager(은행원), Customer(고객)에서 하지 않는 모든 업무를 수행하고 있습니다. Bank클래스를 크게 3가지로 나누면 아래와 같습니다.
1. 은행의 개점과 종료를 사용자에게 입력받아 해당 작업 수행.
2. 임의의 수 생성 후 해당 수만큼 고객을 큐에 넣어주는 작업.
3. 업무를 고객의 요구에 따라 나눠 BankManager가 수행하도록 하는 작업.
- inputMenu: 은행이 개점을 하거나 종료를 할 때 사용자에게 입력에 필요한 정보를 제공하는 메서드
- generateRandomNumberOfCustomers: 프로젝트의 요구사항에 따라 10이상 30이하의 임의의 수를 생성하고 numberOfCustomers 프로퍼티에 대입 역할의 메서드
- insertCustomersIntoQueue: 생성된 임의의 수 만큼 고객을 생성해 큐에 넣어주는 메서드.
- distributeTask: 고객의 요구에 따라 업무를 처리하는 메서드.
- openBank: 사용자로부터 "종료"입력을 받지 않는 이상 계속 은행 업무를 수행하는 메서드.
고객들의 업무를 처리하는 기능을하는 클래스
- handleDepositCustomers: 예금업무에 관한 기능을 담은 메서드 이기때문에 BankManager의 역할에 부합하여 해당 클래스에 구현하였다.
- …
=> 은행 창구 매니저 [STEP3] Kiwi, Kay

.gitignore, BankManager.swift, BankManagerConsoleApp/.swiftlint.yml, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/contents.xcworkspacedata, BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Node.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift, BankManagerConsoleApp/Podfile, BankManagerConsoleApp/Podfile.lock, BankManagerUIApp/BankManagerUIApp.xcodeproj/project.pbxproj, BankManagerUIApp/BankManagerUIApp.xcworkspace/contents.xcworkspacedata, BankManagerUIApp/BankManagerUIApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, BankManagerUIApp/Podfile, BankManagerUIApp/Podfile.lock
@junbangg 
안녕하세요!
반갑습니다 알라딘:) 이번 스탭은 간단했지만 잘 부탁드립니다 :)
1. Node 구현
2. LinkedList 구현
3. Queue 구현
4. CustomerQueueTest 구현
- 테스트시에 private 접근 제어자에 접근할 수 없어, 임시로 접근 제어자를 풀어준 후에 테스트를 하고, 이후 접근제어자를 붙여주었는데 맞는 방법인지가 궁금합니다!!
- 테스트 전
```swift
final class CustomerQueue<T> {
let customerList = LinkedList<T>()
...
}
// 테스트 코드
func test_one을_deque했을_때_Aaron이_나오는지() {
sut.customerList.head = Node(one)
let result = sut.dequeue()
XCTAssertEqual(result, "Aaron")
}
```
- 테스트 후
```swift
final class CustomerQueue<T> {
private let customerList = LinkedList<T>()
...
}
```
```swift
final class CustomerQueue<T> {
private let customerList = LinkedList<T>()
...
}
```
위와 같이 Liked List의 타입을 미리 구현한 다음 은행 방문 손님을 담는 큐에서 해당 타입의 프로퍼티를 구현했습니다.
Customer Queue자체를 Linked List로 할지 해당 타입의 프로퍼티를 내부에 구현할 지 고민 되었지만 어떠한 타입의 정의는 …
=> 은행 창구 매니저 [STEP1] 토털이, 애런

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift, BankManagerConsoleApp/BankManagerConsoleApp/Node.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, README.md
@1Consumption
안녕하세요, 올라프
STEP2 완료되어 PR드립니다.
이번에도 아낌없는 리뷰 부탁드립니다. 🙏🏻
- Bank 타입에서 은행을 열었을 때 처리할 작업을 나타내는 메서드 네이밍을 `open`으로 하려고 하다가 `open`이 시스템 예약어라서 다른 이름을 사용하기 위해 `openUp`이라는 이름으로 설정해 주었습니다.
- UIApp에서 만들었던 파일을 ConsoleApp으로 가져오는 방법을 고민해 보았습니다.
- UIApp에서 만든 Node, CustomerQueue파일을   
ConsoleApp으로 복사하기위해 파일을 끌어서 놨는데   
ConsoleApp의 Node, CustomerQueue파일의 내용을 변경할때 UIApp에서의   
Node, CustomerQueue내용이 같이 변경된다는점을 발견했습니다.   
이를 해결하기 위해여 아래와 같이 진행했습니다.  
finder에서 consoleApp폴더에 복사붙여넣기한상태로,finder에서는 붙여넣기한 파일들이 보이지만
아래사진에서 Xcode에는 반영이 안된걸 알수있습니다.  
(적용이 안된상태)
그래서 finder에 추가한 파일들을 그대로 끌어다가 놓으면 이런 창이 뜨게 됩니다.
여기서 Copy Items if needed를 꼭 체크해주고  
finish를 눌러 파일이 잘 들어온걸 확인할수있었습니다.
이제 더이상 AppUI의 파일과 내용을 공유하지않았습니다.
- 고객업무를 처리하기 위해 Bank 타입의 `allocateCustomer` 메서드에서 customer를`dequeue`로 제거할 때 리턴값을 사용하지 않기 위해 …
=> 은행 창구 매니저 [STEP 2] 망디, 메네

BankManager.swift, BankManagerConsoleApp/.swiftlint.yml, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
@uuu1101 
안녕하세요 태태! 🙌🏼
은행창구 매니저 [STEP 2] p.r을 보냅니다! 잘 부탁드립니다! 🙆🏻‍♀️🙆🏻‍♂️ 
- Bank 내에서 동기 비동기를 사용하여 각각의 은행원에 고객을 할당해야 한다고 생각했는데, 명세서 확인 후 흐름만을 구현하는 것이 목적이라고 판단해서, 명세서 대로 구현하는 것을 목표했습니다!
- 기능 분리를 위해 기존의 startTask() 메서드에서 해주었던 일을, 추가 함수를 만들어 startTask() 내부에서 호출하고자 하였습니다.
- 그 과정에서 고객대기열에 넣어주었던 랜덤한 값을 빼내어주는 일과, 과정을 거쳐 시간을 반환하는 일을 나타내는 메서드명을 고민하여 짓게 되었습니다. 저희가 고심하여 지은 네이밍이 현재 메서드가 하는 일을 나타내기에 적합한지 궁금합니다. 
- 요구 명세서에 충실하고자 [STEP 2] 고객타입내부에 간단한 고객의 수를 가지도록 구현하였는데, 현재 단계에서 고객 타입에 대해 더 구현하거나 적용해야 하는 점이 있는지 궁금합니다.
=> 은행창구 매니저 [STEP 2] Baem, Bella

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/QueueTests.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Node.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/QueueTests/QueueTests.swift
@havilog
안녕하세요 하비! 코낄이, 베토입니다.
은행창구 매니저 프로젝트의 step1 첫 PR 보냅니다. 2주간 잘부탁드립니다! :smile:
처음에 시작할 때 프로젝트 파일을 찾아보니 UIApp과 ConsoleApp 두개로 나누어져있었습니다. 저희입장에서는 처음보는 형태라 어디서 코드를 작성해야할지 몰라서 일단 storyborad가 있는 UIApp프로젝트 파일에서 시작을 하였습니다. 다 작성하고 고민을 해보니 UIApp에서 작성해야 하는지 의문이 들어서 선배기수의 코드를 보고 다른 캠퍼분들의 의견(UI가 없기 때문에 UIApp에서 작성하는 것은 아닌 것 같다는 의견)을 들어서 ConsoleApp 프로젝트 파일에서 시작하는 것이 맞는거 같아서 처음 커밋으로 돌아와 다시 작성하였습니다. ConsoleApp에서 시작하는 것이 맞는지 궁금합니다. 어떤 기준이 있다면 어떤 기준으로 선택해야 하는지 궁금합니다.
UIApp 환경에서 테스트하던것과 마찬가지로 `@testable import`로 테스트 대상의 타겟을 `import`해서 시험하고자 했으나, 다음과같은 에러가 발생했습니다.
`BankManagerConsoleApp` 타겟을 인식하지 못하는 것으로 보여 타겟 설정에서 여러 시행착오를 해봤으나 결국 해결하지 못하고, 다음과 같이 테스트 대상 파일에서 Target Membership을 추가하는 방법으로 테스트했습니다.
그러나 위 방법은 번거로울 뿐더러 같은 프로젝트 내에 있는 타겟을 인식하지 못하는것은 부자연스럽게 느껴집니다.
위 내용과 관련해서 저희가 살펴봐야할 부분이 있을까요? 🤔
=> 은행창구 매니저 [STEP 1] vetto, kokkilE

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/QueueTests.xcscheme, BankManagerConsoleApp/QueueTests/QueueTests.swift, BankManagerUIApp/BankManagerUIApp.xcodeproj/project.pbxproj, BankManagerUIApp/BankManagerUIApp.xcodeproj/xcshareddata/xcschemes/BankManagerUIApp.xcscheme, BankManagerUIApp/QueueTests/QueueTests.swift, Node.swift, Queue.swift
@AppleCEO
안녕하세요 도미닉! 은행창구 매니저 프로젝트 기간 동안 리뷰 잘 부탁드립니다🙂🙂🙂
- Linked List Queue를 구현해주기 위해 Node 클래스를 구현해주었습니다.
- Heap 영역에서 인스턴스가 유지, 관리되어야 하는 Node와 달리, Queue는 필요성을 느끼지 못하여 struct로 구현해주었습니다.
- Queue의 clear 메서드에서 ARC를 고려하여 head와 tail 모두 nil을 할당해주었습니다.
>아래와 같이 테스트 코드 작성 시 `given`과 `when`에 무엇을 적어야할지 고민했습니다. `given`은 어떤 상황이 주어지고, `when`은 어떤 코드를 실행한다고 배웠습니다. 그렇다면 `enqueue`메서드는 `given`인지, `when`인지 궁금합니다!
```swift
// 1번
func test_dequeue됐을경우_처음_enqueue된_데이터가_반환된다() {
// given
let expectation = "hello"
// when
sut.enqueue("hello")
sut.enqueue("kaki")
sut.enqueue("songjun")
let result = sut.dequeue()!
// then
XCTAssertEqual(result, expectation)
}
// 2번
func test_dequeue됐을경우_처음_enqueue된_데이터가_반환된다() {
// given
let expectation = "hello"
sut.enqueue("hello")
sut.enqueue("kaki")
sut.enqueue("songjun")
// …
```
=> 은행창구매니저 [STEP1] kaki, 송준

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerUIApp/BankManagerUIApp.xcodeproj/project.pbxproj, BankManagerUIApp/BankManagerUIApp/BankQueue.swift, BankManagerUIApp/BankManagerUIAppTests/BankManagerUIAppTests.swift
@lina0322 안녕하세요 엘림! STEP1 PR 보내드립니다.
- Linked-list에 단방향, 양방향 중에서 메모리 절약을 위해 단방향 Linked-list를 사용하였습니다.
- 은행창구 프로젝트의 사이즈나 디테일한 구현정도를 알지못해서 일단 단방향리스트만으로 충분할거같다는 생각이 들어서 단방향 리스트로 구현했습니다.
=> 은행창구매니저 [STEP 1] Goat, Andrew

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/QueueTests/QueueTests.swift, BankManagerUIApp/QueueTests/QueueTests.swift, Queue.swift
@AppleCEO
안녕하세요 도미닉! Step2 PR입니다! 이번 리뷰도 잘부탁드립니다!
- Step2 요구사항에 맞게 구현을 완료하였습니다.
- 메뉴에 없는 숫자를 눌렀을 시 에러를 처리해주는 과정을 추가해줄지 고민하였는데, 요구사항에 없는 내용이라 따로 구현하지 않았습니다.
- 고객이 총 몇명인지 확인할 수 있게 Queue 내부에 `size` 프로퍼티를 추가해주었습니다.
- BankManager 구조체 내부에 `setupWaitingQueueAndClientNumber`, `startBusiness`메서드가 있습니다.
- 이 메서드 내부에는 여러기능들이 존재합니다. 크게보면 업무시작과 함께 기능하는 작동들이라 한 메서드에 정의해주었는데, 이 기능들을 세분화할 경우 main에서 코드를 진행시킬 때 여러 함수들을 실행시켜야 해서 고민이 됩니다.
- 기준을 크게 잡아 한 번에 실행시킨 지금의 방식이 좋을지, 아니면 조금 더 세분화하여 여러개의 함수를 실행시키는 방식이 좋을지 조언 주시면 감사하겠습니다.
```swift
mutating func setupWaitingQueueAndClientNumber() {
for number in 1...Int.random(in: 10...30) {
waitingQueue.enqueue("\(number)번 고객")
}
clientNumber = waitingQueue.size
}
mutating func startBusiness() {
while !waitingQueue.isEmpty {
guard let client = waitingQueue.dequeue() else …
```
=> 은행창구 매니저 [STEP2] kaki, songjun

BankDesk.swift, BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/TextEnum.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerUIApp/BankManagerUIApp.xcodeproj/project.pbxproj, BankManagerUIApp/BankManagerUIApp/ViewController.swift, BankQueue.swift, Extension.swift, README.md
@lina0322 안녕하세요 엘림! 은행창구 매니저 STEP2 PR 보내드립니다!
step1에서 추가 코멘트 주신 부분들은 step2에서 반영하고 코멘트 다시 달아두었습니다ㅎ
이번 리뷰도 잘 부탁드리겠습니다
-> **struct -> class 변경으로 해결**
* BankManager는 처음에 struct로 구현했는데, 클로저에서 self키워드 사용시 위와같은에러 **Escaping closure captures mutating 'self' parameter**라는 에러가 나왔습니다
* 찾아보니 DispatchQueue의 클로저 안에 구현된 self가 struct구조(값타입)의 값을 전달받아오거나 변경할 수 없다는 내용으로 이해했습니다.
* 따라서 구조체에서 참조타입으로 class로 변경해 위와같은 에러를 해결했습니다
*  지금은 `BankManagerUIApp` 프로젝트를 사용하지않지만 저희는 처음에 Queue를 UI쪽에 구현했습니다. 그러나 이번스텝은 `BankManagerConsoleApp`콘솔앱에 요구사항이 있었습니다. 콘솔앱에 프로젝트를 진행하는 외에도 추후에 UI앱쪽에도 `BankQueue`와 `BankManager`를 사용할 일이 있을거같아 위처럼 두개의 파일을 공동파일로 위치를 변경해주었는데 적절할까요?
-> `BankQueue`를 UIApp폴더 내에서 ios-bank-manager 파일로 이동
- sleep과 usleep은 기능은 같지만 usleep 초단위를 좀 더 세밀하게 동작할 수 있다는 차이점이 있습니다. 
- 초 단위를 0.7초 주어야 하는데 sleep은 Int 데이터형식으로만 …
=> 은행창구 매니저 [STEP 2] Goat, Andrew

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankClient.swift, BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift, BankManagerConsoleApp/BankManagerConsoleApp/Business.swift, BankManagerConsoleApp/BankManagerConsoleApp/BusinessType.swift
@havilog
안녕하세요 하비! 코낄이, 베토입니다.
step3 구현을 다 하고 PR 보냅니다.
Swift에서 동시성을 구현하는 방법으로는 GCD, Operation 두 가지 방법을 고려했습니다. 
GCD는 Swift의 동시성 구현 방법으로 가장 먼저 등장한 기본적인 방법이고, Operation은 GCD를 기반으로 더 객체지향적으로 등장한 개념이라고 합니다.
저희는 동시성 프로그래밍의 개념을 처음 접하기 때문에, 가장 기본적인 GCD를 활용한 방법으로 구현해보았습니다.
저희는 총 인원을 `numberOfClient`라는 변수에 `clientQueue`가 `dequeue` 될 때마다 늘려주고 최종적인 인원이 `numberOfClient`에 들어가면 `numberOfClient` 변수에 `0.7`을 곱한 숫자를 총 업무시간으로 출력하였습니다.
하지만 step3의 동시성 프로그래밍을 하면서 기존의 산출 방법으로 동시에 수행되는 작업들의 총 업무시간을 나타내기엔 힘든 부분이 있었습니다.
따라서 현재는 `Foundation` 내장 함수인 `CFAbsoluteTimeGetCurrent()`을 활용하여 작업을 수행하기 전에 시간을 구해주고 작업이 전부 끝난 뒤 시간을 구하여 그 차이를 나타내는 식으로 코드를 작성하였습니다.
```swift
private func measureProcessTime(_ process: () -> ()) -> Double {
let startTime = CFAbsoluteTimeGetCurrent()
process()
let processTime = …
```
=> 은행창구 매니저 [STEP 3] vetto, kokkilE

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankMangerQueueTests.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/Node.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/BankMangerQueueTests/BankMangerQueueTests.swift, BankManagerConsoleApp/BankMangerQueueTests/TestPlan.xctestplan
은행창구매니져 [STEP 1] Kobe, Hamg
안녕하세요 그린(@GREENOVER)! 🙌
이번에 은행창구매니저 리뷰를 받게 된 Kobe, Hamg 입니다.🙋‍♂️
첫 PR을 보내게 된 날이 우연히도 복날이네요 :)
맛있는 식사 시간 되시길 바랍니다.🍗 
리뷰 잘 부탁드립니다!🙇🏻‍♂️
1️⃣ 링크드리스트와 큐의 구현
지난 프로젝트 중 계산기 프로젝트에서 단방향 링크드 리스트를 활용하여 큐를 구현한 경험이 코비와 햄지 모두 있었습니다.
그래서 함께 회의를 한 결과 큐 내부에 링크드 리스트를 구현하는 것이 조금 더 실용적이라고 생각을 했습니다.
그러나 제약사항을 다시 꼼꼼하게 읽어본 결과 링크드 리스트를 따로 빼서 구현해야 한다는 점을 알게 되었고, 프로젝트의 목적성을 다시금 알게 되었습니다.
그 관계성에서 큐와 링크드 리스트를 분리하는 과정 속에서 고민을 많이 했던 것 같습니다.
2️⃣ XCTest 진행이 안되었던점
XCTest파일을 만들고 테스트를 진행하려고 했는데 알수없는 에러가 발생하여 문제가 되었습니다. 테스트를 하려고 진행시에 알수없는 타입이라 생각을 하게 되었고 Model로 만들었던 `Queue`, `LinkedList`, `Node` 등 모두 `Targer Membership`에서 Tests에 대한 체크를 진행하여 테스트 시에 알수있게 하게끔 진행하였고 Model을 알 수 있었기에 테스트가 진행 되었습니다.
1️⃣ 테스트 구현 과정
현재 테스트 구현과정이 콘솔 앱에서 맞게 이루어지는 궁금합니다.
알 수 없는 에러 속에서 타겟 멤버십의 타겟을 체크해가면서 해결한 테스트 구현과정이라 저희도 이것이 …
=> 은행창구 매니저[STEP 1] Kobe, Hamg

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/LinkedListTest.xcscheme, BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/CustomerWatingQueue.swift, BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Node.swift, BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift, BankManagerConsoleApp/QueueTest/QueueTest.swift
@havilog
안녕하세요. 하비~
이번에 하비의 리뷰를 받게 된 `karen`입니다. 편하게 '카렌'이라고 불러주시면 됩니다.😊
은행창구 매니저 `Step01` `PR`보내드립니다.
최대한 코드를 작성할 때 왜 이렇게 작성하게 되었는지 한번 더 생각해보면서 작성을 해보았습니다.
2주 동안의 은행 창구 매니저 프로젝트 리뷰 잘 부탁드립니다.🙇🏻‍♀️
**<고민한 부분>**
- 이 부분은 예전 '계산기'라는 프로젝트를 진행할 때도 의문이었던 부분이었는데 명확하게 해답을 찾지 못하고 지나갔었습니다. 그때는 **자료구조를 왜 사용해야되는지가 가장 큰 의문**이었고, 자료구조라는 것에 아직 익숙하지 않고 제대로 이해를 못했기 때문이라고만 생각하고 넘어갔었습니다. 그런데 이번 프로젝트에서 또 다시 맞닥뜨리니 이번에는 **명확한 이유를 알고 작성을 해야되겠다는 생각**이 들었습니다.
- 의문점은`LinkedList`도 `Queue`도 자료구조의 한 종류이고 심지어 안에 구성도 메소드명만 다르지 역할은 동일하다 생각되어졌고, '**하나만 구현하면 되는 것 아닐까**?'라고 생각되어졌습니다. 왜 굳이 `LinkedList`를 활용해서 `Queue`를 또 작성을 해야되는지에 대해 의문이 들었습니다.
**<두 자료구조의 차이>**
- **`Queue`**
- 선입선출(`FIFO`)
- 자료를 갖는 컨테이너 프로퍼티가 반드시 필요
- 삽입과 제거를 빠르게 수행하기 위해 사용
- `enqueue`(삽입) : `Queue`의 뒤쪽에 요소를 추가
- `dequeue`(제거) : `Queue`의 앞쪽에서 요소를 제거
- …
=> 은행창구 매니저 [STEP 1] karen

BankClerk.swift, BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankClerk.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
@YebinKim 
안녕하세요 븨븨!😆
Erick & Serena 조입니다⭐️
은행창구 매니저 프로젝트 Step2 PR 보냅니다.
리뷰 잘 부탁드립니다~!
-----
은행 개점을 하여 고객 업무 처리를 은행원이 진행합니다. 이 모든 것을 은행매니저가 총괄합니다.
> 주요 내용 : Command Line, sleep(), Date()
-----
- 실제 은행을 생각하며 은행 `Bank`, 은행원 `BankClerk`, 고객 `Customer`, 그리고 이를 모두 총괄하는 은행매니저`BankManager`로 나누어 구현하였습니다.
- `Customer`은 자신의 대기 번호와 업무 시간을 가지고 있고, `BankClerk`은 이를 이용하여 은행 업무 시작, 완료를 하도록 했습니다.
- `Bank`은 은행원과 고객의 숫자 그리고 대기줄을 가지고 있으며 고객을 줄 세우고, 은행원을 이용한 전체 은행 서비스를 수행하도록 했습니다.
- 마지막으로 `BankManager`는 `Bank`를 가지고 있고 관리하는 프로그램 영역의 객체라고 생각하여 메뉴의 출력, 선택과 `Bank`를 초기화하는 로직을 담당하도록 했습니다.
- 스텝2를 구현함에 있어서 고객의 업무를 처리하는 데 걸리는 시간 0.7초를 딜레이를 시켜야했습니다. 이를 구현하는데 `DispatchQueue`를 활용한 방법과, `sleep`메소드를 활용한 방법 두가지 중 어떤 방식을 사용할지 고민했습니다.
- `DispatchQueue`의 `global` 메소드를 사용하면 업무의 시작 함수(`startTask`)와 업무 종료 알림 함수(`endTask`)가 서로 다른 …
=> 은행창구 매니저 [STEP 2] Erick, Serena

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankClerk.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, README.md
안녕하세요 Steven! @stevenkim18 
와이🍰 & 비모🤖입니다.
은행창구 매니저 Step2 PR 전송합니다!
이번 스텝도 잘 부탁드립니다 😆😁
---
```swift
func work(customerNumber: Int) {
print("\(customerNumber)번 고객 업무 시작")
Thread.sleep(forTimeInterval: 0.7)
print("\(customerNumber)번 고객 업무 완료")
}
```
위 메서드에서 스레드를 0.7초간 멈추기 위해 `Thread.sleep(forTimeInterval:)`를 사용했습니다. 해당 메서드를 사용한 이유는 다음과 같습니다.
1. `sleep(_: UInt32)` 함수를 이용하려고 했으나, 함수의 파라미터로 `UInt32`타입을 받았기 때문에 소수점이 필요한 0.7초는 지정할 수 없었습니다.
2. `usleep(_: useconds_t)` 함수는 세부적인 시간을 지정할 수 있었으나, `1000000`이 1초를 의미했기 때문에 직관적으로 알아보기 어렵다고 생각했습니다.
[Thread.sleep(forTimeInterval:)](https://developer.apple.com/documentation/foundation/thread/1413673-sleep)
=> 은행창구 매니저 [STEP 2] yyss99(와이), 비모

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/Bank/Teller.swift, BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Queue.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/QueueTest/QueueTest.swift, README.md
@havilog
안녕하세요. 하비~
은행창구 매니저 `Step02` `PR`보내드립니다.
아직까지는 동기, 비동기에 관련된 사항을 적용할 `Step`은 아닌것 같다고 생각되어져서 이번 `Step`에서는 객체지향적으로 생각해서 역할을 분배하는데에 초점을 두고 코드를 작성해보았습니다.
이번 리뷰도 잘 부탁드립니다.😊
- 업무 처리시간을 고객이 가지고 있는게 맞을지 은행원이 가지고 있는게 맞을지 고민되었습니다. 고객이 어떤 업무를 할지를 가져오는거니까 고객이 요청하는 업무에 따라 처리 시간이 달라지니 고객이 가지고 있는게 맞는건가라고 잠깐 생각했었는데 은행원에게 고객이 업무를 전달하고 그 업무를 처리하는 것은 은행원이니까 업무 처리시간을 갖는 것은 은행원이 맞다고 생각되어졌습니다.
- 시간에 대해 적용시켜보는 것은 처음이라 어떻게 주어져야할지 고민되었습니다. 검색해보니 `sleep`과 `Thread.sleep`이렇게 두 가지가 있었습니다. 두 가지 모두 같은 기능을 한다고 되어있었는데 차이는 아래와 같습니다.
|**메서드명**|**내 용**|
|:-:|-|
| sleep    |`static`타입 메서드 <br>  `sleep`은 마이크로초(1/1000000초) 단위로 대기 시간을 지정  |
|Thread.sleep|`class`타입 메서드 <br> `Thread.sleep`은 밀리초(1/1000초) 단위로 대기 시간을 지정 |
- 이러한 차이로 인해 `Thread.sleep`을 사용할 때 대기 시간을 더 쉽게 조정할 수 있습니다.
- 또한 `Thread.sleep()`이 `Foundation …
=>  은행창구 매니저 [STEP 2] karen

BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer/Customer.swift
안녕하세요, 하비@havilog!
Step 2를 빠르게 확인해주신 덕분에 Step 3도 바로 작업할 수 있었습니다! 감사합니다🙇‍♀️
이번 스텝도 잘 부탁드립니다!
은행 업무가 `예금` / `대출` 두 가지로 나뉘고 이에 따라 업무 처리시간과 출력메시지도 달라지게 되어, 해당 내용을 `Work`라는 타입으로 분류하였습니다.
이 `Work`는 은행 내부의 업무이기 때문에 `Bank` 안에 `Nested` 처리를 해주었습니다.
```swift
enum Work: CaseIterable {
case deposit
case loan
var duration: Decimal {
switch self {
case .deposit:
return 0.7
case .loan:
return 1.1
}
}
var name: String {
switch self {
case .deposit:
return "예금"
case .loan:
return "대출"
}
}
}
```
❓ 한 가지 여쭤보고 싶은 점은 `Customer` 인스턴스가 각자 진행할 업무를 프로퍼티로 소유하고 있어야 해서 해당 프로퍼티의 타입은 `Bank.Work` 형식이 되었는데, 이런 방식으로 접근하는게 문제가 될지 궁금합니다.
```swift
struct Customer: Equatable {
let bankWork: Bank.Work
let waitingNumber: Int
}
```
`2명의 은행원은 예금업무를, 1명의 은행원은 대출업무를 처리`에서 업무별로 `OperationQueue`를 나눠서 생성하여 각각의 `Queue`의 `Thread`수를 조절해주면 …
=> 은행창구 매니저 [STEP 3] - kyungmin, maxhyunm

BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/BankManager/BankService.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Banker.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankManager/CustomerQueue.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Model/BankingServiceTimeConverter.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Model/Enum/BankManagerNameSpace.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Model/Enum/BankingOperations.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Model/TimeCheck.swift, BankManagerConsoleApp/BankManagerConsoleApp/Error/NumberFormatError.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift
안녕하세요 그린(@GREENOVER)!
더운 여름 KWDC에서 아주 좋은 연사였습니다!!😍
고생 많으셨습니다!!🙇🏻‍♂️
스유에 대해서 잘모르지만 뭔가 배워보고싶고 해보고싶은 동기부여를 얻게 되었습니다.🙌
이번 리뷰를 받게 된 Kobe, Hamg 입니다. 잘 부탁드립니다!
- 이번 스탭에서 은행원이 3명이라 지정을 해줘서 Banker에 3명을 주어 2명은 예금을 하게끔 1명은 대출을 하게끔 진행해야한다고 생각했습니다.
```swift
for _ in 1...depsit {}
for _ in 1...loan {}
```
- 이런식으로 예금, 대출에 맞게 진행을 해야하나 생각하면서 스텝을 진행하려고하였고 생각처럼 방법을 구현하지를 못했습니다. 그래서 다른 방법으로 예금큐, 대출큐 를 구현하여 진행 하고자 했습니다
```swfit
depositBankerQueue = OperationQueue()
loanBankerQueue = OperationQueue()
depositBankerQueue.maxConcurrentOperationCount = 2
loanBankerQueue.maxConcurrentOperationCount = 1
```
- 이런식으로 구현을 하게 되면 대출,예금따로 진행을 하게 되는것을 알게되었는데요, 이렇게 된다면 `Banker`가 하는일이 없어지게 되었는데요 이렇게되면 이번 스텝에 있어 잘못알고 진행을 하게 된걸까요? 이상이없이 구현을 해낸거라면 `Banker` 를 지우는게 맞을까요??
저희가 코드를 구현하면서 콘솔로만 확인하다보니 제대로 구현이 되었는지 확인하는 방법에 많은 고민을 …
=> 은행창구 매니저 [STEP 3] Kobe, Hemg

BankManager.swift, BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj, BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/BankingService.swift, BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift, BankManagerConsoleApp/BankManagerConsoleApp/SingleLinkedList.swift, BankManagerConsoleApp/BankManagerConsoleApp/TotalTimeFormatter.swift, BankManagerConsoleApp/BankManagerConsoleApp/main.swift, BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift, README.md
안녕하세요 제임스(@inwoodev)!
EtialMoon, idinaloq입니다!
스탭3 리뷰도 잘 부탁드립니다~
- 메서드의 매개변수에 메서드의 역할과 관련없는 전달인자가 있었습니다.
처음 작성한 코드는 다음과 같습니다.
```swift
struct BankManager {
func work(for customer: Customer, group: DispatchGroup, semaphore: DispatchSemaphore) { ... }
}
struct Bank {
private mutating func processBusiness() {
var depositBankManagerNumber = 0
let group = DispatchGroup()
let semaphore = DispatchSemaphore(value: 3)
let startDate = Date()
}
```
`GCD`를 활용하기 위해 `processBusiness`메서드 내부에서 프로퍼티를 만들고 이를 `work`메서드에 전달인자로 전달했는데, 이렇게 되면 결국 `BankManager`가 `work`라는 동작을 할 때 필요없는 정보들을 넘겨주는 것 같다고 생각했습니다. 이 부분에 대해서는 다음과 같이 수정을 했고, 결과적으로 `Dispatch Queue`를 사용하기 위한 프로퍼티들이 `processBusiness`메서드를 실행할 때 마다 계속해서 생성되지 않게 되었고, `BankManager`가 `work(for: customer)`라는 동작을 할 때 어떤 기능인지에 대해 명확하게 나타낼 수 있게 되었다고 생각합니다.
```swift …
```
=> 은행창구 매니저 [STEP3] EtialMoon, idinaloq

BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift, BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift, README.md
@havilog
안녕하세요. 하비~
은행창구 매니저 `Step03` `PR`보내드립니다.
이번 `Step`에서의 핵심은 비동기 처리였고, 동기와 비동기를 이해하는데 많은 시간을 소요한 것 같습니다.
최대한 이해하고 구현해보았습니다.
아직 많이 부족하겠지만 하비께서 해주시는 조언과 피드백을 거름 삼아 성장해보도록 하겠습니다.
많은 가르침 부탁드립니다.🙏🏻
- 이번 프로젝트의 비동기 처리를 어떤걸 활용해서 해야될 지 고민을 많이 했습니다. 
- `Operation Queue`는 `KVO`를 통해 작업의 상태 변화를 관찰하고, 작업간의 의존성 관리와 작업 취소, 일시 중지, 재개 등과 같은 기능을 제공해주어 의존성을 명시적으로 관리할 수 있는 장점이 있어 `Dispatch Queue`보다 메모리적으로 효율성이 더 좋을것 같았지만, 실상은 작업을 생성한 큐의 내부 스레드 풀을 활용하여 작업을 실행하고 관리하는 `Dispatch Queue`가 경량적인 구조로 스레드를 생성하고 사용하므로 메모리 사용량이 낮고 작업이 큐에 추가되면 더 작은 단위로 분할하여 처리하는 것이 가능한 `Dispatch Queue`가 작업을 더 효율적으로 관리할 수 있는 등 이점이 많아 `Dispatch Queue`를 선택하게 되었습니다.
- 또한 현 프로젝트에서는 우선 순위 기반으로 작업을 처리하는 것도 아니고 대기 시간이라는 것이 주어지기는 하지만 프로젝트 명시상 작업시간이 긴 대출 업무가 먼저 끝나게 하는것도 아니기에 `KVO`를 통해 작업의 상태 변화를 관찰하고 추적할 필요성은 없는 것 같아 `Operation Queue`를 적용시키는 …
=> 은행창구 매니저 [STEP 3] Karen
