- Bank.swift
- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Dashboard.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Enum.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Teller.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
안녕하세요🙇🏻‍♀️
- BankManager -> 은행
은행 업무를 시작하고 끝내는 역할
은행원에게 고객(업무)을 나눠줌
- Teller -> 은행원
주어진 업무를, 시간에 맞게 처리
- Client -> 고객
어디부터 어디까지 은행이 담당할지 고민했습니다.
업무처리 자체는 은행원이 하고,
업무를 나눠주는 것은 은행이 할 수 있도록 시도해보았습니다.
~차후에 0.7초 걸리는 업무외에도 추가된다면
고객은 업무의 이름을, 은행원은 해당 업무 이름에 따른 시간을 확인할 수 있는 방법으로 구현할까 생각만 했습니다.~
실제로 콘솔에서 0.7초가 지연되도록 구현하고 싶었습니다.
timer와 dispatchQueue과 usleep에서 고민했는데 우선은 usleep을 사용했습니다.
3번에서 사용한 dispatchQueue가 올바른 방법이라면, 이 지연시간도 dispatchQueue로 구현하고 싶습니다.. ~(아직은 너무 감이 안잡혀요)~🌪
뭔가... 동기 비동기를 해야할 것 같다는 생각이 막연히 드는데, 정확히 어떻게 구현을 해야할지 모르겠습니다. 
일단 시도는 해봤는데, 이렇게 하는게 맞는지 모르겠습니다.
(이를 확인하기 위해서 현재 업무처리 문구가 약간 다릅니다.
3번 고객 업무 시작[기획서] -> 1번 창구 : 3번 고객 업무 시작[실제 코드])
우선 발생한 문제는 은행원들이 업무를 마감하기 전에 메뉴가 다시 나온다는 것입니다. 이것을 우선 usleep을 이용하여 시간지연을 주었더니 해결은 되었는데, 마찬가지로 맞는 방식인지 모르겠습니다.
동기 비동기와 관련해서 어떤걸 보면 좋을까요🥺
처음에는 main 함수에서 …
> Step 1 : 타입 및 Console App 구현 (리나)

- Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Dashboard.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Enum.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Teller.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
1. Client 정렬을 위해 `Priority` 생성 후 priority를 기준으로 Comparable extension하여 sorted 할 수 있도록 함
2. BusinessType에 loan 추가
3. Client를 생성할때 allCases.randomElement()를 사용하여 priority와 businessType을 랜덤하게 생성
4. 은행원은 3명으로 증원
리뷰 부탁드립니다🙇🏻‍♀️
> Step 2 : 우선순위와 다중처리 (리나)

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
**BankManager** 
- 은행원 Clerk, 고객 Customer 
- 은행원 명 수 만큼 Dispatch Queue를 생성하여 일을 할당해주도록 구현하였습니다. (clerks)
( 은행원의 index 를 label 로 붙여서 custom dispatch queue를 생성하도록 하였습니다. default 설정이 serial 큐라서 따로 속성을 명시하거나 바꾸지는 않았습니다. )
- 각 은행원은 작업시간(processTime), 총 작업시간(totalTime)을 가지고 있도록 하였습니다.
( dispatch queue 에 DispatchSpecificKey를 이용하여 value 를 세팅해두는 방식으로 )
- 고객은 아직까지 번호만 필요한거 같아 따로 class 나 struct 로 빼지 않고 번호들을 들고 있는 Int 배열(customers)을 사용하였습니다.
- 은행이 업무를 시작하는 open() 내에서 assignCustomer()를 호출하여 각 은행원(queue)에 첫 고객을 비동기로 할당해주고, 이 후로는 재귀를 통해 각 은행원이 알아서 고객 대기열에서 자신에게 고객을 할당하도록 하였습니다 ( 이 때, 각 큐의 업무 시작과 끝을 알기 위해 bankTaskGroup이라는 이름으로 DispatchGroup을 생성하여 시작시에 group.enter(), 모두 끝마쳤을 때(=더이상 할당할 고객이 없을 때) group.leave()를 호출해 주었습니다. )
- 비동기로 각 큐에 고객을 할당하고 나면 해당 open() 함수가 바로 끝나버리는데, 은행원들이 일을 모두 마칠때까지 기다릴 수 있도록 …
> STEP 1 찌루루

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerTest.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankManagerError.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- BankManagerConsoleApp/BankManagerTest/BankManagerTest.swift
- BankManagerConsoleApp/BankManagerTest/Info.plist
- README.md
@AppleCEO 
안녕하세요, 도미닉! 한 주동안 열심히 관련 내용을 학습하고 코드를 작성하여 Step 1 PR을 보냅니다!
이번 주에는 `Process`와 `Thread`, `Operation`과 `OperationQueue`의 개념을 익히고 적용하는데 주안점을 두었습니다. 도미닉의 의견을 듬뿍 담아 따끔한 피드백을 많이 받을 수 있으면 좋겠습니다! 😄
- 프로그램 사용자가 프로그램을 시작하고 종료할 수 있는 기능을 제공합니다.
- `selectMenu() throws -> Int`: 사용자의 입력을 받아 입력한 숫자를 반환합니다. 정수가 아닌 입력을 할 경우 에러를 throw합니다.
- `move(to:)`: 선택된 메뉴로 이동합니다.
- `start()`: 프로그램을 시작합니다. 메뉴 선택 시 발생한 에러에 대한 에러 처리를 수행합니다.
- 인스턴스 생성 시 이니셜라이저를 통해 `Bank` 타입에서 근무할 은행원의 수를 설정할 수 있습니다.
- 은행 개점과 마감, 업무 처리 시 총 소요 시간을 계산하는 기능을 제공합니다.
- 인스턴스 생성 시 입력 받은 `numberOfTeller` 전달 인자를 통해 한 번에 처리할 `Operation` 수를 설정합니다(`OperationQueue.maxConcurrentOperationCount`).
- `makeClients(number:)`: 입력 받은 수만큼 `Client` 인스턴스를 만들어 배열에 넣은 후 결과를 반환합니다.
- `measureTime(_:) -> Double`: 전달 인자로 입력받은 클로저 내부에 입력된 메서드의 처리에 걸리는 시간을 …
>  🏦 은행 매니저 [STEP 1] 💸 Yun, Ryan

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankManagerError.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankingTask.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- BankManagerConsoleApp/BankManagerTest/BankManagerTest.swift
안녕하세요. 도미닉!  Step2는 변경 사항이 별로 없어 PR을 빨리 보내게 되었어요. 이번 PR도 잘부탁드립니다🙇
1. 은행원의 수를 `watingQueue`(OperationQueue)의 `maxConcurrentOperationCount`프로퍼티로 설정하도록 구현하였습니다.
2. `Client` 타입이 `Client`의 업무를 처리하는 것은 논리적으로 맞지 않다고 생각하여, 이번 버전에서는 `Client` 타입에 `Operation`클래스를 상속한 `BankingTask` 프로퍼티를 추가하여 구조를 파악하기 쉽도록 변경하였습니다.
-  `Operation`을 상속받은 클래스로써 `Client`타입인 owner프로퍼티의 업무진행상황을 출력합니다.
-  main()메서드로 업무를 처리합니다.
- `Task`타입 열거형을 통해 은행업무 종류를 정의합니다.
-  은행은 고객의 우선순위에 따라 대기 중인 고객 중 우선순위가 높은 고객을 먼저 응대합니다.
- `Grade`에 `Comparable` 프로토콜을 채택하여 case 간에 우선순위를 부여하였고, `sortByGrade(for:)` 메서드를 이용하여 `client.grade`를 기준으로 정렬을 수행하였습니다.
- Step 2의 은행에는 3명의 은행원이 근무합니다.
- 은행원의 수를 `waitingQueue`의 `maxConcurrentOperationCount`프로퍼티로 생각하였습니다.
- 고객은 다음의 우선순위 등급이 있습니다.
- `Client` 타입내부의  Grade 열거형통해, 고객의 우선순위를 정의하였습니다.
- 고객이 원하는 업무의 종류와 …
> 🏦은행 매니저💸[Step-2] Yun, Ryan

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- BankManagerConsoleApp/QueueMethodTest/Info.plist
- BankManagerConsoleApp/QueueMethodTest/QueueMethodTest.swift
비비 안녕하세요~~~!! 질문을 정리하다보니 어느새 이렇게 많아졌네요...😭 잘 부탁드립니다!!!!
@YebinKim 
1. Queue를 구현할 연결리스트를 단일연결리스트와 이중연결리스트 중 무엇으로 만들지 고민했습니다.
1. 프로젝트 요구사항을 구현하는 데는 이중연결리스트의 추가적인 기능이 필요하지 않다고 생각해 단일연결리스트로 구현하기로 하였습니다. 
- 이중연결리스트의 특성상, 노드를 Head와 Tail 각각에서 양방향으로 접근할 수 있는데 현재 기능 요구사항에서는 굳이 필요하지 않다고 생각했습니다. 이중연결리스트를 구현하는 경우 메모리를 많이 차지해 메모리 효율이 낮아지므로 단일연결리스트를 사용해 구현하는 것이 더욱 좋다고 판단했습니다.
2. 코드의 가독성을 위해 `head`, `tail` 노드로 명명하였습니다. 
1. 처음엔 head만 있어도 된다고 생각했지만 날라의 의견을 들어보니 head, tail로 나눈 것이 직관적이라는 것에 동의하였습니다. 
1. head :  첫 Node 인스턴스 
2. tail : 마지막 Node 인스턴스 
3. `Queue`와 `LinkedList` 클래스를 나눈 이유
1. 처음엔 `LinkedList` 로 구현했습니다.
2. 프로젝트 명세서에 Queue와LinkedList 타입을 구현하라고 하였기 때문에 위와 같이 하였는데 프로젝트 명세서에 없었다면 Queue 타입안에 LinkedLIst 타입을 한꺼번에 구현해도 되지않을까하는 생각이 듭니다. 
4. `Node`, `LinkedList`, `Queue` 구현 시 클래스 와 구조체 중 어느것으로 해야하는지 궁금해서 …
> 은행창구 매니저[Step1] Nala, Tacocat

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
- BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
안녕하세요 도미닉! @AppleCEO 
은행 창구 매니저 Step 1 마무리되서 PR 보내드립니다! 
이번 프로젝트 잘 부탁드립니다 🙏 
감사합니다 🙇 
- Linked List 맨 마지막에 원소를 조금 더 효율적으로 추가하기 위해 `tail` 변수를 생성했습니다.
- Linked List를 Queue의 타입으로 이용할 수 있게 스텝 요구사항이었던 `Enqueue, Dequeue, Clear, Peek, isEmpty` 를 Linked List 내부에 구현했습니다. 
후에 동료들과 이야기하다가 Queue 타입을 따로 구현하는게 맞다고 판단해서 Queue 타입을 추가로 구현했습니다. 
Linked List도 그에 맞추어 네이밍을 수정했습니다.
- Linked List의 `removeAll()` /  `removeFirst()`메서드의 로직을 고민했습니다.
```swift    
mutating func clear() {
while head != nil {
head = nil
head = head?.next
}
}
```
처음에는 위 코드처럼 head가 nil이 아닐 때, head에 nil을 할당해주고 head를 `head?.next`로 이동시켜서 모든 원소를 돌며 일일히 삭제해주는 방법을 사용했습니다.
하지만 LLDB를 통해 확인해보니 head에 nil을 할당한다면 이어지는 모든 Node도 nil이 할당되어 전부 비워지는 것을 확인했습니다. tail에는 저희가 직접 특정한 Node를 할당해주어 `head = nil` 만으로는 nil이 할당되지 않는 것을 확인할 수 있었습니다. 
head에 추가한 Node가 …
> 은행 창구 매니저 [STEP 1] yeha, 호댕

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/QueueTest.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/OperatingTimeManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
@protocorn93 
@Kim-EunsooSilver
step2 PR제출합니다!
많은 고민과 시행착오가 있었는데 PR에 잘 담겼는지 모르겠네요 😂
이번 리뷰도 잘부탁드립니다!
감사합니다☺️
---
- Banker타입을 처음에는 인원수를 고려하지 않고 구현했다가, n명의 은행원이 있다는 요구사항을 확인하고 Bank타입 안에서 bankers라는 배열로 정의했습니다.
- 은행의 업무시간을 계산하기 위해 Timer 클래스 사용에 대한 고민을 했습니다. 저희가 수시간 동안 연구(?) 해본 결과 저희의 상황에는 맞지 않는 방식으로 결론을 내렸고 `CFAbsoluteTimeGetCurrent()` 를 사용하여 은행의 업무시간을 계산하였습니다.
- Timer클래스를 사용한다면 프로그램을 실행하는 내내 0.01초마다 timeCount라는 변수에 0.01씩을 더해주는 방식을 생각했었는데, 이렇게 된다면 실행하는 동안 계속적으로 0.01초마다 연산이 반복되기 때문에 지금처럼 처음과 끝시간만을 이용해서 한번만 계산하는 것이 더 효율적이라고 생각했습니다.
- BankManager와 Main의 역할에 대한 고민을 했습니다. 프로젝트 포크시에 기본 생성된 파일이기에 파일명에 맞게끔 설계했습니다.
- 총업무시간 계산결과를 소수점둘째자리까지 나타내기 위해서 NumberFormatter를 사용했습니다.
- 메뉴에서 1을 선택했을 때 작업을 실행하고 2를 선택했을 때 종료를 하는 부분에서 wile문을 사용한 이유
- 1을 선택해서 작업이 수행이 끝난 뒤에 다시 메뉴를 호출해서 새롭게 은행을 개점해야할 수도 있는데, 이부분을 isExit와 …
> 은행 창구 매니저 [STEP2] 호랭이, 니콜라스

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankTeller.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- BankManagerConsoleApp/Tests/QueueTestDouble.swift
- BankManagerConsoleApp/Tests/Tests.swift
@aCafela-coffee @hoBahk
안녕하세요 쿠마! @leejun6694 
두 번째 PR도 잘 부탁드립니다 🙏🏻
```swift
var queue = Queue<Int>()
queue.enqueue(1)
queue.enqueue(2)
var queue2 = queue
queue2.enqueue(3)
// dequeue 예상
queue.dequeue() // 1
queue.dequeue() // 2
queue.dequeue() // 3
// dequeue 예상
queue2.dequeue() // 1
queue2.dequeue() // 2
queue2.dequeue() // 3
```
`Queue`가 구조체라면 위 상황이 문제입니다.
`Queue`의 인스턴스는 다르지만 `Node`의 참조가 같아서, 다른 큐에 영향을 미치게 됩니다.
같은 이유로 `Bank`도 `class`여야 합니다.
```swift
private let semaphore: DispatchSemaphore
let group = DispatchGroup()
while let client = clients.dequeue() {
DispatchQueue.global().async(group: group) {
self.semaphore.wait()
self.respond(to: client)
self.semaphore.signal()
}
}
group.wait()
```
은행 업무 로직을 `Dispatch Queue`를 사용하여 코드를 구현하였습니다.
`DispatchGroup`을 사용하여 비동기 작업들을 그룹화 해주고 모든 작업이 끝날 때 …
> 은행 창구 매니저 [STEP2] 요한, aCafela coffee, 호박

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Banker.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- README.md
안녕하세요 델마 @delmaSong  🙌🏻
아리 @leeari95 , 허황 @hwangjeha입니다.
은행 창구 매니저 프로젝트 STEP 3 구현 완료해서 PR 보냅니다. 
저번에 와주셔서 직접 코드리뷰해주셔서 덕분에 많은 도움이 되었어요. 감사했습니다! 😆 
궁금했던 점, 조언이 필요한 부분 이 외에 저희가 놓친 부분이나 부족한 부분이 있다면 번거롭더라도 한번 더 짚어주시면 감사하겠습니다.🙏🏻
- 여러 은행원이 동시에 고객의 일을 처리하는 로직을 고민해봤습니다.
1. `global() 큐`에 은행원의 수 만큼 `task`를 만들고 각각의 `task`에서 고객을 `dequeue`해서 처리하는 방식
2. 하나의 while 구문에서 dequeue 해주고 고객의 은행 업무에 따라 예금 고객은 `DispatchQueue.global()`에 세마포어를 이용해 `은행원 수 == 접근 가능한 스레드 수`  만드는 방식
- `DispatchSemaphore`의 `value`를 1이 아닌 2나 3으로 줄 경우 `Race Condition`이 발생할 수 있다는 가능성이 존재하기 때문에 해당 방법은 적절하지 못하다는 생각이 들었습니다.
- `Banker`가 가지고 있는 `work()` 메소드는 현재 공유자원에 접근하고 있지 않지만, 추후 해당 메소드가 공유자원에 접근하지 않을거라는 보장이 없다라는 생각이 들었습니다.
- 추후 은행원의 수가 변경되더라도 대응할 수 있도록 은행원 수 만큼 `DispatchQueue.global()`에 `task`를 만드는 `1번 방식`으로 구현했습니다.
- `은행원 수` == …
> 은행 창구 매니저 [STEP 3] 아리, 허황

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankPrinter.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Task.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
안녕하세요 찰리 @kcharliek 🙇‍♀️
은행 창구 매니저 Step 3 완료하여 PR 보내드립니다.
잘 부탁드립니다! 👍
은행원의 수를 쓰레드라고 생각하였고, 고객의 업무 종류에 따라 depositQueue, loanQueue를 만들어주었습니다. 
depositQueue는 concurrent하게 loanQueue는 serial하게 만들었습니다.
while문의 조건으로 customerQueue에서 customer을 dequeue하는 것을 설정하여 공유자원에는 한 번씩만 접근하도록 설계하였습니다. 
deposit 케이스에서는 비동기적으로 동작하는 concurrent 큐에서
semaphore를 사용하여 동시에 접근가능한 스레드의 수를 2로 두어서 deposit을 처리하는 은행원이 동시에 두명이 되도록 구현하였습니다. 
반면에 loan 케이스에서는 일을 처리하는 은행원이 한 명이기때문에 비동기적으로 동작하는 serial큐를 사용하였습니다. 
```swift
static func createRandomTask() -> Self {
guard let task = Self.allCases.randomElement() else {
fatalError("랜덤한 Task를 생성할 수 없습니다.")
}
return task
}
```
`Task` enum 에서 랜덤한 task를 열거형의 모든 case에서 골라서 리턴해주는 메서드에서 `fatalError()`을 사용하였는데요, 처음에는 error enum을 따로 만들어줘서 에러처리를 해주려고 했지만, 로직상 절대 발생할 수 없는 에러이기때문에 에러처리가 불필요하다고 생각하여 …
> 은행 창구 매니저 [STEP 3] 제인, 차차

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankTask.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/ConsoleBundle.swift
- README.md
안녕하세요! 그린 @GREENOVER 
릴리, 숲재입니다! 
스텝3 구현완료하여 PR요청드립니다😊
- 시도했던 방법
`distributeClient`메서드에서는 BankClerk객체가 클라이언트 Queue를 순회하며 BankClerk이 가지고 있는 `workType`과 Client의 `workType`이 동일할때만 `remove`메서드를 사용하여 꺼내옵니다. BankClerk 객체를 순회하며 서로 다른 쓰레드에서 비동기적으로 `distributeClient`메서드를 수행하도록 시키는 방법으로 구현했습니다. "예금-예금-예금-대출" 이런 순서로 고객이 존재할때 대출 담당 은행원이 놀고있는 시간을 방지하기 위해서 이렇게 구현하였는데, 고객의 수가 많아지는 경우 탐색 시간이 길어져 불완전한 설계라고 판단하였습니다.(고객이 5만명 정도를 넘어가면 유의미하게 실행시간이 길어지는 것을 확인하였습니다.) 
```swift
private func makeBankClerksWork() {
let group = DispatchGroup()
for bankClerk in bankClerks {
DispatchQueue.global().async(group: group) {
self.distributeClient(to: bankClerk)
}
}
group.wait()
}
private func distributeClient(to bankClerk: BankClerk) {
while !self.clientQueue.isEmpty {
semaphore.wait()
var i = 0
while let client = …
```
> 은행 창구 매니저 [STEP 3] 릴리, 숲재

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/QueueTest.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankingType.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
@protocorn93 
@Kim-EunsooSilver
안녕하세요 콘! 
step3 PR 제출합니다
목표기한이 아직 남기는 했지만, 
더 많은 조언을 받으면서 수정할 부분을 찾아보고 싶어서 조금 일찍 PR을 제출하게됐습니당😊
항상 최고의 리뷰 감사해요 👍
이번에도 잘부탁드리겠습니다!!
---
- Bank타입 내부의 `doWork()` 메서드의 로직 구현에 많은 고민을 했습니다. for문, async 코드 블럭, while문, if문 등이 한 메서드 내에서 쓰이다 보니까 안그래도 어려운 로직짜기가 더 헷갈려서 많은 시간이...걸렸습니다...
- 은행 업무에 대해서 타입으로 구현하고 사용하는 방법에 대해서 고민을 했습니다.
- Banker 내부의 `task`를 두개 (예금, 대출) 만들어, 실행 하는 부분에서 분기를 이용하여 선택된 `task` 내부에서 `sleep`을 주는 의견
- Banker 타입 내부의 `task`를 한개 만들어, 내부에서 전달받은 고객의 업무를 이용해 분기하여 `sleep`을 주는 의견
→ 우리의 결론...
1. 소요시간을 타입 내부에서 정의
`BankingType`에 따른 소요시간은 `BankingType`과 함께 정해져있는 것이기 때문에, 코드에서 사용하면서 분기문 등에서 숫자로 입력해주는 것보다는 `BankingType`내부에서 정의해놓고 이 타입을 이용해서 가져다 쓰는 것이 바람직하다는 생각에 현재와 같이 구현했습니다.
2. `Banker` 타입 자체에 `assignedTask` 프로퍼티를 만들어서 사용
`Banker` 타입 자체에 …
> 은행 창구 매니저 [STEP3] 호랭이, 니콜라스

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankWork.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Employee.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Funtional Type/Speaker.swift
안녕하세요, 찰리~!! @kcharliek 
Step3의 PR 요쳥드립니다🙏
마지막까지 잘 부탁드립니다!!
1-1. BankWorkType.allCases.ramdomElement() 옵셔널 바인딩을 어떻게 해줄 것인가를 고민했습니다. 아래 두 가지 중, BankWork가 빈 열거형이 아니기 때문에 문제가 없다고 판단하여 후자 (강제 언래핑)를 선택했습니다.
```swift
var requestedWork: BankWork {
guard let work = BankWork.allCases.randomElement() else {
return BankWork.loan
}
return work
}
```
```swift
var requestedWork: BankWork {
BankWork.allCases.randomElement()!
}
```
1-2. 업무의 시작과 종료를 구분짓기 위해서 async와 asyncAfter로 분리되는 작업을 하나로 변경해주었습니다.
- 이때 시작 단에서 찾은 first와 종료 단에서 찾은 first가 다른 것을 확인하였습니다.
- 시작단에서 dequeue를 해주면서 반환값을 받고, 받은 값을 종료 메서드의 파라미터에 넣어서 해결하였습니다.
1-3. Step2에서 사용되었던 `asyncAfter`는 `Thread.sleep()`으로 변경하였습니다.
- asyncAfter를 사용하였을 때의 문제
while문 내부에 위치한 비동기 작업이 멈추는 동안, 계속 조건을 확인하는 while에 의해 group1.enter()가 만 회 가까이 불리게 됩니다. 그러나 그 횟수에 미치지 못하는 …
> 은행 창구 매니저 [STEP3] Zoe, 고사리

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankClerk.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
안녕하세요. 흰! @daheenallwhite
아샌(@ICS-Asan), 신나(@smart8612) 입니다. 
프로젝트 STEP3 PR 올립니다! 
이번 스텝은 지적할 부분이 많을 것 같다고 생각이 됩니다😭
어떠한 피드백이라도 저희에게 도움이 많이 될 것 같습니다.
많은 지적과 조언해주시면 같이 고민하고 공부해보겠습니다.
감사합니다!!
- 은행 업무에 대한 타입을 생성
- 업무에 따른 작업시간이 다르기 때문에 각 작업별로 걸리는 시간을 연산프로퍼티로 구현
- 출력문에서 해당 업무에 대한 문자열을 받기 위한 연산 프로퍼티 구현
- Customer인스턴스 생성시 작업을 random하게 갖도록 하기 위해 타입 메서드 구현
- 손님이 어떠한 업무를 보고싶은지 가지고 있어야 한다고 판단하여 task프로퍼티를 생성
- 손님이 생성될 때 생성자 내부에서 랜덤한 은행 업무를 갖도록 구현
- 업무별 은행원(DispatchQueue)을 관리하기 위해 DispatchQueue의 배열을 타입으로 갖는 프로퍼티를 생성
- `예금부서(depositDepartment)`, `대출부서(loanDepartment)`로 구분
- 생성자를 통해 부서별 은행원의 수를 지정하여 은행원(DispatchQueue)을 생성
- 은행원의 수가 변경되는 경우를 고려하여 코드 구현
- 내부에서 반복되는 코드를 줄이기 위해 DispatchQueue의 배열을 생성하는 부분을 private 타입메서드를 통해 구현
- 은행원 1명은 한번에 1가지 일을 하도록 하기 위해 Serial로 생성
- 업무에 따른 은행원(DispatchQueue)을 배정하기 위해 …
> 은행 창구 매니저 [STEP 3] 아샌, 신나

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/.swiftlint.yml
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Presentable.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Util/BankError.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Util/Constants.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
@Monsteel 
안녕하세요 토니!!!
STEP2 구현 완료하여 PR 보내드립니다!!
잘 부탁드립니다🙇‍♂️
---
- Client 타입 구현
- Bank 타입 구현
- BankClerk 타입 구현
- BankManager 타입 구현
---
---
---
- 범용적으로 사용되는 constants가 존재할 수 있다는 것을 고려하여 네임스페이스로서 활용할 Constants 타입을 생성하였습니다.
- BankClerk.swift와 BankManager.swift에서 발생하는 매직넘버와 매직스트링을 Constant extension을 통해 각각의 파일에서 바로 확인 가능하도록 가독성을 높여주었습니다.
- 이런 경우에 Constants는 UML에서 어떻게 표현해야하는지 궁금합니다. 토니는 어떤식으로 표현하시나요?!
- BankClerk이 작업을 완료하면, Bank는 마감메시지를 출력해야합니다.
- BankClerk이 작업을 완료하면 Bank의 close()메소드가 실행되도록 하는데, 결합도를 낮추기 위해 delegate pattern을 적용해보았습니다.
- GCD를 학습하고, 사용을 해보고자 현재로서는 불필요한 코드들이 들어가면서 코드가 많이 지저분 해진 것 같습니다😭
- 해당 부분에서 workItem의 코드블럭, 메서드의 수행 시간 측정하는 부분들을 메서드로 분리해볼 수 있을 것 같다 라고까지만 생각을 해본 것 같습니다.
- 이 부분은 토니에게 피드백을 받고 수정하는게 좋을 것 같아 우선 남겨두었습니다!
- 현재 은행원이 작업시간이 0.7초가 걸리는 요구사항이 있습니다.
- 해당 요구사항을 반영하기 위해 …
> 은행 창구 매니저 [STEP2] 파프리, 마이노

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankClerk.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
- README.md
@jungseungyeo
안녕하세요. 린생
Safari, Donnie입니다.
은행창구 [STEP 3] PR 보냅니다.
```swift
// BEFORE
switch task {
case .deposit:
depositWindow.wait() // <- 서로의 로직에 영향 🚨🚨
DispatchQueue.global().async(group: group) {
self.bankClerk.processTask(for: customer)
depositWindow.signal()
}
case .loan:
loanWindow.wait() // <- 서로의 로직에 영향 🚨🚨
DispatchQueue.global().async(group: group) {
self.bankClerk.processTask(for: customer)
loanWindow.signal()
}
}
```
```swift
// AFTER
switch task {
case .deposit:
depositWindowQueue.addOperation {
self.bankClerk.processTask(for: customer)
}
case .loan:
loanWindowQueue.addOperation {
self.bankClerk.processTask(for: customer)
}
}
// 중략...
// 최대 은행원 수 (= 사용할 쓰레드 수)
func assignClerkCount(at deposit: OperationQueue, and loan: OperationQueue) {   
deposit.maxConcurrentOperationCount = …
```
> 은행 창구 매니저 [STEP3] Safari, Donnie

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankService.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/BankServiceType.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Presentable.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Util/Constants.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
@Monsteel 
안녕하세요 토니!!!!
STEP3 구현 완료하여 PR 요청 드립니다!!!
잘 부탁드립니다!!!🙇‍♂️
---
- BankService: 은행 업무와 관련된 Enum
- 업무에 따른 고객 큐 분리
- 업무에 따른 은행원 업무 할당
- 비동기 처리
---
---
---
- 이전 스텝에서 조언해주신걸 토대로 Constants를 재구성 해보았습니다. 토니가 말씀해주신 부분이 맞을까요?!
이번 프로젝트에서는
고객(`Client`)의 은행업무(`BankService`)에 따라
해당 업무를 담당하는 은행원(`BankClerk`)이 해당 고객의 업무를 처리 할 수 있어야 했습니다.
이를 위해`Bank` 의 프로퍼티로
`private let depositClientQueue = Queue<Client>()`
`private let loanClientQueue = Queue<Client>()`
를 두었습니다.
추후에 은행업무가 다양해지거나, 은행원이 담당할 수 있는 업무가 하나 이상이 되는 경우 새롭게 Bank에 해당 업무를 보기위한 고객들의 큐를 프로퍼티로 두어야하고, 코드 안에서 수정해야하는 부분이 많음을 느꼈습니다.
좀 더 확장이 유연하게 될 수 있도록 수정하고 싶은데, 이를 위해 공부할만한 키워드를 던져주실 수 있으실까요?!
* Xcode의 기본 기능인 Thread Sanitizer을 통해 Data Race가 발생하는지 확인하였습니다.
위의 이미지와 같은 Threading Issue를 확인 할 수 있었습니다.
- 해당 부분을 해결하기 위해 linkedList의 removeFirst() 메서드에서 …
> 은행 창구 매니저 [STEP3] 파프리, 마이노

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankClerk.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Queue.swift
- BankManagerConsoleApp/BankManagerConsoleApp/WorkType.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Workable.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- README.md
@hyunable  안녕하세요 혀나!! 
이번 STEP도 잘부탁드리겠습니다! 🥳
---  
---  
1️⃣ 재활용성과 확장성에 대한 고민
- 이번 프로젝트에선 업무가 2개(예금, 대출)이지만, 후에 업무가 추가되고 그에 따라서 직원이 새로 배치된다고 가정했다. 
- 이때, 코드의 수정을 최소화하고, 확장에 용이하도록 구현하는 것이 목표였다.
- 첫번째 시도
1) 직무 별로 직급을 두고 직급별로 객체를 구현하는 것을 시도했다.  
2) 만약 이럴 경우 타입이 늘어날수록 중복코드가 늘어난다는 문제가 생긴다. 
3) 이를 해결하기 위해 class를 통한 상속을 이용해야한다. 
4) superClass로 `Worker`를 두고 중복되는 코드를 구현한다. 
5) 그리고 업무별 직원 class에 `Worker`를 상속시킨다.
6) 장점: 직무가 늘어나도 class만 추가만 해주면 되기 때문에 확장성이 매우 용이하, 직무별 달라지는 업무 내용은 `override`를 통해 수정할 수 있다. 
7) 단점: class로 구현하게 되어 RC 증가로 인해 많은 비용이 든다.
- 두번째 시도
1) `BankClerk` 구조체를 유지하고, class를 사용하지 않는 방법으로 시도했다.
2) 문제는 `client.wantedWork`(고객 업무)에 따라 `Clerk`의 업무 내용도 달라져야 한다는 점이었다.
3) 이 문제를 해결하기 위해서 `WorkType` enum을 만들어줬다.
4) 직무가 늘어난다면 enum에 csae를 추가하는 것만으로 `BankClerk` 객체에 업무라는 특성을 쥐어줄 수 있다.
5) `BankClerk`에 …
> 은행 창구 매니저 [STEP3] mmim, malrang

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Queue/ClientQueue.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue/Node.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue/Queue.swift
- README.md
@leejun6694
안녕하세요, 쿠마!🥰 
은행창구매니저 프로젝트 9조 민쏜과 데릭입니다.
Step 1 PR 보냅니다. 
아래와 같이 작업내용과, 저희의 생각의 흐름을 작성해보았습니다.
저희가 생각한 방향에 대해 쿠마는 어떻게 생각하시는지 피드백 부탁 드립니다! 😁
- `ClientQueue` 타입 구현을 위한 단방향 `LinkedList` 타입을 구현했습니다.
- 단방향 LinkedList이지만 tail 속성을 정의하여 새로운 요소가 추가될 때마다 tail을 업데이트 하고 있습니다.
- 요소를 추가할 때마다 head에서 tail까지 순회하는 것을 방지하기 위함입니다.
- `ClientQueue` 타입은 다양한 타입의 데이터를 취급할 수 있도록 스위프트의 Generics 기능을 활용했습니다.
- `ClientQueue` 타입의 정상 동작 여부를 Unit Test를 통해 검증했습니다.
```swift 
mutating func enqueue(_ data: Element) {
queue.append(Node(data))
}
```
```swift 
func dequeue() -> Node<Element>? {
return queue.isEmpty() == true ? nil : queue.removeFirst()
}
```
```swift 
func clear() {
queue.removeAll()
}
```
```swift 
var peek: Element? {
return queue.head?.data ?? nil
}
```
```swift 
func isEmpty() -> Bool {
return …
```
> 은행 창구 매니저 [STEP1] minsson, derrickkim0109

- .gitignore
- BankManager.swift
- BankManagerConsoleApp/.swiftlint.yml
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/contents.xcworkspacedata
- BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList+extension.swift
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue+extension.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
- BankManagerConsoleApp/Podfile
- BankManagerConsoleApp/Podfile.lock
- BankManagerConsoleApp/QueueTest/QueueTest.swift
안녕하세요 우디! ☺️ @Wody95 
STEP1 PR 보내드립니다!
잘 부탁드립니다~🙏
---
---
```shell
Could not find module 'BankManagerConsoleApp' for target 'x86_64-apple-
macos'; found: arm64-apple-macos, 
at:/Users/Kim-DongYong/Library/Developer/Xcode/DerivedData/BankManagerConsoleApp-
acslyqhrplbojmgnotygnhtucvdv/Index/Build/Products/Debug/BankManagerConsoleApp
.swiftmodule
```
이번 프로젝트에서 `UnitTest`를 진행하면서 `@testable import`를 해주려고 했습니다.
그런데, Command line tool 프로그램을 만들때 M1 맥북을 사용하는 경우는 위와 같은 에러가 발생하며, 작동하지 않는 것을 발견했습니다.
어찌저찌 `@testable`을 적어주지 않고, 각 파일에서 직접 Target Membership을 체크해주는 것으로 해결하였는데요, 이렇게 해결하는 것이 올바른 방법이 아니라는 생각이 들어 어떻게 해결하면 좋을지 질문드립니다 🥲
1. `class vs struct`
- `Queue` 타입과 `LinkedList` 타입을 초반에는 class로 구현했었습니다. 하지만 `Sequence`, `IteratorProtocol` 프로토콜을 채택해서 구현하는 과정에서, `next()` 메서드가 호출 될 때, 다음 노드를 가르키는 …
> 은행 창구 매니저 [STEP1] Bard, Finnn

- .gitignore
- BankManagerConsoleApp/.swiftlint.yml
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/contents.xcworkspacedata
- BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- BankManagerConsoleApp/Podfile
- BankManagerConsoleApp/Podfile.lock
- BankManagerConsoleApp/QueueTests/QueueTests.swift
안녕하세요. 제임스(@inwoodev)! 이번 프로젝트 리뷰를 부탁드리게 된 애종, stone입니다!
이번 스텝에서는 대기열(큐, Queue) 타입만 구현하면 되어서 내용은 많지 않지만 잘 부탁드립니다!
- Node
- data
- 해당 Node의 값을 담는 프로퍼티입니다.
- next
- 다음 Node의 값을 담는 프로퍼티입니다.
- LinkedList
- head
- LinkedList의 첫번째 Node입니다.
- tail
- LinkedList의 마지막 Node입니다.
- headData
- 첫번째 Node의 값을 가져오는 연산프로퍼티입니다.
- isEmpty
- LinkedList가 비어있는지 확인할 수 있는 연산프로퍼티입니다.
- appendNode(_ value: T)
- LinkedList의 끝에 값을 append하는 함수입니다.
- removeHead() -> T?
- LinkedList의 첫번째 값을 제거하고 반환하는 함수입니다.
- removeAll()
- head와 tail을 nil로 할당함으로써 초기화하는 함수입니다.
- Queue
- peek
- LinkedList - headData를 호출하는 연산프로퍼티입니다. 
- isEmpty
- LinkedList - isEmpty를 호출하는 연산프로퍼티입니다.
- enqueue(_ item: T)
- LinkedList에 값을 추가하는 함수입니다.
- dequeue() -> T?
- LinkedList에서 값을 가져오고 가져온 값을 제거하는 함수입니다.
- clear
- linkedList의 내부 요소를 초기화하는 함수입니다.
- 이번 …
> 은행창구 매니저 [STEP 1] 애종, stone

- .gitignore
- BankManager.swift
- BankManagerConsoleApp/.swiftlint.yml
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/ManagerQueueTests.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/contents.xcworkspacedata
- BankManagerConsoleApp/BankManagerConsoleApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- BankManagerConsoleApp/ManagerQueueTests/CustomerQueueTests.swift
- BankManagerConsoleApp/Podfile
- BankManagerConsoleApp/Podfile.lock
안녕하세요 Tony(@Monsteel) 🙌🙌🙌🙌
이번 프로젝트 같이 하게 된 zhilly랑 미니입니다.
Step1 구현 완료되어서 PR 발송합니다.
> `Queue 타입 구현을 위한 Linked-list 타입을 직접 구현합니다.`의 의미
지난번 큐를 구현하는 과제에서는 Linked-list를 구현하는 방식을 활용하여서 큐를 구현하였습니다. 하지만 `Queue 타입 구현을 위한 Linked-list` 라는 구문을 보고 Queue를 구현하기 위한 새로운 타입을 구현하라는 의미인지에 대해서 고민하게 되었습니다. 이에 대해서 추상적인 자료구조를 구현하기 쉽고, 재사용성을 높일 수 있는 Linked-list 타입을 구현하였습니다. 또한, Linked-list 타입을 구현함으로써 재사용성을 높이는 것과 다른 코더가 보았을 때 이해하기 쉬운 코드 중 어떤 것을 활용해야 더 적절한 것인가에 대해서 고민했습니다.
> LinkedList는 `struct` vs `class`
LinkedList 타입을 정의하기 위해서 어떤 사용자 정의 타입을 활용하는 가에 대해서 고민하게 되었습니다. 저희가 사용하는 Node 타입은 ARC를 이용해서 관리 해줘야 한다고 생각했습니다. 하지만, LinkedList는 큐 타입 내부에서 선언되어서 활용되는 변수이기 때문에 ARC로 관리되지도 않고, 추가적인 상속을 구현하지 않을 것이라고 생각하였습니다. 그래서 애플에서 기본적으로 struct를 사용하라고 권장하기 때문에 우선적으로 struct로 구현하였습니다.
> `SwiftLint` 라이브러리를 SPM으로 관리할지, CocoaPods으로 관리할지 …
> 은행창구 매니저 [STEP 1] zhilly, 미니

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/QueueTests.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
- BankManagerConsoleApp/QueueTests/QueueTests.swift
@lina0322
안녕하세요, 엘림! 은행 창구 매니저에서 함께하게 된 준호, 웅입니다.
STEP-1 구현하여 PR보냅니다.
* Node
- 데이터를 저장해줄 data 변수 / 다음 데이터의 주소값을 저장해줄 next 변수로 구성하였습니다.
- 다음 Node의 주소값을 저장하기 위해 struct대신 reference type인 class로 구현하였습니다.
- data 프로퍼티는 외부에서 접근하여 읽기만 하기 때문에 private(set) 키워드를 추가했습니다.
- Node 클래스는 더 이상 상속하지 않기때문에 class 앞에 final 키워드를 추가했습니다.
* LinkedList
- Node를 연결한 자료 구조형을 만들었습니다.
- class로 구현해줄 마땅한 이유가 없어서 struct로 구현하였습니다.
- 첫 노드를 가리키는 head와 마지막 노드를 가리키는 tail 프로퍼티를 만들었습니다.
- head와 tail 프로퍼티에는 구현한 범위 밖에서 접근하지 못하도록 private 키워드를 추가했습니다.
- 첫 노드의 값을 반환하는 firstValue 와 LinkedList가 비었는지 확인하는 isEmpty 연산 프로퍼티를 만들었습니다.
- 끝에 노드를 추가하는 addLast(), 첫 번째 노드를 빼는 removeFirst(), 모든 노드를 지워주는 removeAll() 메서드를 만들었습니다.
* Queue
- 요구사항에 따라 isEmpty, enqueue, dequeue, clear, peek을 구현하였습니다.
- 다양한 데이터를 취급할 수 있도록 Generic 타입을 활용하였습니다.
* …
> 은행창구 매니저 [STEP 1] woong, 준호

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankingService/BankingService.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Console.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Person/Banker.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Person/Customer.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue/CustomerQueue.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue/Queue.swift
- BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
안녕하세요, 그린(@GREENOVER)🙇‍🙇‍🙇‍♀️!
[Som☁️](https://github.com/jsa0224), [Ayaan🦖](https://github.com/oneStar92), [Dragon🐉](https://github.com/FlameYG)입니다!
저희 Step 3 구현 완료하여 PR 보냅니다!😁
나름대로 비동기적 처리를 고민하여 구현해봤습니다...😵‍💫
부족한 부분이 많지만 좋은 리뷰 부탁드립니다!!!🙇🏻‍♂️
- 무작위의 BankingServicce를 가진 상태의 고객들을 어떻게 분리할 것인가
1. CustomerQueue를 loanQueue, depositQueue 2개로 만들어 고객들을 정렬
2. CustomerQueue에서 BankingService에 맞는 가장 빠른 순서를 가진 고객을 dequeueFirst하는 메서드를 추가적으로 구현
→ Queue의 특성인 FIFO를 고려하여 1번이 더 적절하다고 판단하여 구현하였습니다. 
- `Completion` 사용
- `DispatchQeueue`의 `global()`에서 async로 은행원이 업무를 처리한 후 다음 업무를 어떻게 처리해야할지 많은 고민을 했습니다.
1. Delegate와 같은 패턴을 사용하여서 은행원이 업무가 끝나면 끝났음을 알리고 다음 고객을 전달받는 방식
2. Completion으로 `@escaping` 클로저를 통해서 업무가 끝난 후 다음 작업을 이어서 수행하는 방식
- Completion을 통해서 하나의 Task가 종료된 후 다음 Task를 이어서 수행하도록 구현하여 업무가 이어져서 처리되게 구현했습니다.
- …
> 은행 창구 매니저 [Step 3] som, Dragon, Ayaan

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankClerk.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Common/CFAbsoluteTime+.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- README.md
@junbangg
안녕하세요!
반갑습니다 알라딘:) 이번 스탭도 잘 부탁드리겠습니다! 💪🏽
- 고객, 은행, 은행원 타입 구현
- 은행 내에 `open()`, `close()`, `menu()` 구현
- 은행에서 10~30사이의 랜덤한 명수의 손님들을 생성
- 은행에서 은행원이 손님들을 처리하도록 로직 구현
- `CFAbsoluteTimeGetCurrent()` 을 사용하여 시작 및 종료 시간을 측정해서 완료시에 보여주도록 함
- `CFAbsoluteTime`의 extension으로 fomat된 2자리 소수점의 string을 반환하도록 구현
스위프트의 런타임 시간 지연방법중 `sleep()`메서드를 사용해 진행했지만 `Duration`타입의 파라미터에서 1초 미만의 시간을 설정하는데 어려움을 겪었습니다.
Dispatch group을 사용하는 방법과 Timer를 사용하는 방법등 여러 방법을 사용해보다 
`usleep()` 메서드를 사용해 구현했습니다.
```swift
func work(for customer: Customer) {
print("\(customer.number)번 고객 업무 시작")
usleep(useconds_t(700000))
print("\(customer.number)번 고객 업무 완료")
}
```
- `DispatchQueue.main.asyncAfter()`을 사용하려 했지만 제대로 동작하지 않았고, DispatchGroup을 사용하여 이렇게 구현을 할 수 있는데, 불필요하다고 생각이 되어 일단 `usleep()`으로 구현을 해 주었습니다.
```swift
func work(for …
```
> 은행 창구 매니저 [STEP 2] 토털이, Aaron

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Task.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- BankManagerConsoleApp/Pods/Pods.xcodeproj/project.pbxproj
@uuu1101 
안녕하세요 태태! 🙌🏼
은행창구 매니저 [STEP 3] p.r을 보냅니다! 잘 부탁드립니다! 🙆🏻‍♀️🙆🏻‍♂️ 
- 예금 업무와 대출 업무를 `DispatchQueue.global().sync` 로 보내게 될 경우에, 예금 업무와 대출 업무가 동시에 처리되지 않고 하나씩 처리되어 프로젝트의 요구사항과 맞지 않다고 생각되어, `async`로 처리하게 되었습니다. 
- 예금과 대출 업무를 `global.async` 를 이용하여 보낼 경우에, 랜덤하게 생성한 고객 수 만큼(필요한 만큼) 쓰레드를 생성하게 되었습니다. 이를 해결하기 위해, `DispatchSemaphore`와 `SerialQueue` 두 가지 방법 중에 고민하게 되었으며 예금 업무와 대출 업무의 쓰레드의 개수를 DispatchSemaphore의 value 를 이용하여 지정해주게 되었습니다. 
- 처음 `예금 큐` `대출 큐` 를 따로 만들어서 사용하고자 하였습니다. 그러나, Bank 타입 내부에 예금 매니저 2명과 대출 매니저 1명을 생성했고, 예금 매니저에게 예금 큐에 들어있는 고객을 처리하도록 구현해보았으나 구현에 실패하게 되었습니다.🥲
그래서, 일단은 구현에 목적을 두고 고객대기열을 단일 큐로 만들었으며 고객을 enqueue() 할 때에 예금과 대출 업무를 랜덤하게 넣어주게 되었습니다. 
- 앞서 큐의 사용에서 기재한 내용과 이어지는 부분입니다. `BankManger` 를 은행원이라 생각 한 후 예금처리하는 은행원 2명, 대출 처리하는 은행원 1명이라 생각하고 `Bank` 타입을 은행 창구라고 생각해서 은행원들을 처리해주는 …
> 은행창구 매니저 [STEP 3] Baem, Bella

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/BankManagerQueue.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
@forestjae
안녕하세요 숲재!
은행창구 매니저의 두번째 PR을 보내게 된 브로디, 해리, 크리스티입니다.
이번에도 잘 부탁드리겠습니다!😄
큐의 모든 업무가 끝나면 업무를 처리한 고객수와 총 업무시간을 출력해주는 기능이 있었습니다.
업무시간을 **고객의 수 * 0.7** 로 계산을 해서 단순히 출력을 시켜주는 것이 좋을까? 아니면 실제로 업무를 처리를 하는 것을 측정을 하는 것이 좋을까? 고민을 했습니다.
- 결론
- **고객의 수 * 0.7**의 계산식은 실제 업무처리 시간이 아닌 예측을 하는 것이라 생각했습니다.
- 따라서 Core Foundation의 `CFAbsoluteTimeGetCurrent()`를 사용해서 시작시간을 구하였습니다.
- 업무 처리가 끝나는 시간에서 이전에 시작시간을 빼주어 총 소요시간을 측정했습니다.
<br>
처음에는 은행이 문을열고 닫는 것이라고 생각해서 `BankManager`를 사용하지 않고 `Bank`파일에 은행에 관련된 기능을 담고, main파일에서 은행을 열지말지를 정하는 코드를 작성했습니다.
하지만 `main`파일 내에서 은행을 말지열지를 정하는 것보다 `BankManager`가 이 행동에 대해 책임을 지는 것이 좋다고 생각했습니다. 
따라서 `BankManager`객체에서 `Bank`의 인스턴스를 소유해, 사용자의 입력에 따라 `Bank`를 열지 말지 선택할 수 있게 만들었습니다.
<br>
> 은행창구매니저 [STEP 2] brody, christy, harry

- BankManager.swift
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
- BankManagerConsoleApp/BankManagerConsoleApp/ClientWaitingLine.swift
- BankManagerConsoleApp/BankManagerConsoleApp/main.swift
- README.md
@1Consumption
안녕하세요 올라프!⛄️⛄️⛄️⛄️ 
STEP3 PR 보냅니다.
다중처리하는 부분에 있어서 반복되는 코드가 생겨 어려움이 있었던 것 같습니다.
항상 바쁘신 와중에 리뷰해주셔서 감사합니다. 
이번에도 리뷰 잘 부탁드립니다.
감사합니다.⛄️
step2에서 손님 정보는 외부에서 생성자로 주입해줘도 좋을 것 같다는 조언을 얻어
```swift=
private mutating func manageClientQueue() -> Queue<Client> {
var clientQueue = Queue<Client>()
let randomClients = Int.random(in: 10...30)
....
```
수정후 아래와 같이 조금 더 직관적인 코드로 보기 좋게 수정되었습니다. 
```swift=
var bank = Bank(clientCount: Int.random(in: 10...30))
...
init(clientCount: Int) {
self.clientCount = clientCount
}
```
코드를 수정하고나서 무슨 문제인지ㅠ 고객의 수가 지정되어 업무를 마감하고 다시 은행 개점을 하면 같은 고객의 수가 반복되어 지정되는 문제가 발생하게 되었습니다. 해당 부분은 어떤식으로 해결해야할지 몰라서 원상태로 돌려뒀는데 원인을 알고싶습니다ㅠ
업무는 동시적으로 처리가 되지만, 업무시간은 모든 업무의 누계로 나오는 문제가 발생하고 있습니다. 그러한 문제로 인하여 리팩토링을 하려고 하는데, 저희 코드 로직의 문제인지 아니면 `endTime.timeIntervalSince(startTime)` …
> 은행 창구 매니저 [STEP 3] Rhode, sehong

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/Model/Bank.swift
- BankManagerConsoleApp/Model/BankClerk.swift
- BankManagerConsoleApp/Model/Client.swift
- BankManagerConsoleApp/Model/Task.swift
- README.md
@uuu1101
안녕하세요 태태~! 드디어 STEP3 PR을 보내네요...!
뭔가 이번 스텝 진행하면서 초반에 했던 생각이 다 바뀌는 바람에 많이 헤맨 것 같아요...🥲
그럼 리뷰 기다리고있겠습니다😊!
---
> 은행에는 3명의 은행원이 근무합니다(예금담당 2명, 대출담당 1명)
- 은행에는 은행원이 세 명 근무하도록 안내되어있었습니다. `BankClerk`타입을 구현 해 놓은 후라서 "세 개의 global 스레드 안에 각각 BankClerk 인스턴스를 만들어주면 되지 않을까?" 생각을 했습니다. 
- 저희가 처음 생각한 부분은 은행이 은행원에게 대기줄에 있는 손님들을 async로 줄세워주고, 손님들을 받은 은행원들은 동기적으로 일을 처리한다고 생각했습니다.
그래서 은행이 client의 watingLine에서 dequeue하여 bankClerk에게 전달하는 행위자체를 `DispatchQueue.global().async { }` 로 구현하였습니다. 
그리고 client를 전달받은 `BankClerk()`이 3명이 존재하므로 3개의 `DispatchWorkItem`안에 `BankClerk()` 인스턴스를 각각 만들어주었고, client의 방문 목적에 따라 if문을 통하여 deposit/loan으로 나뉘어 세 개의 스레드 중 해당 업무를 처리하는 `BankClerk()`이 존재하는 스레드로 보내주었습니다.
- 위와같이 생각하고 구현을 한 결과, 다음과 같은 문제들이 발생했습니다.
1. deposit 목적의 client는 두 개의 스레드를 거쳐서 중복으로 출력된다.
2. 세 개의 스레드 안에 존재하는 …
> 은행 창구 매니저[STEP3] 리지, 무리

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp.xctestplan
- BankManagerConsoleApp/BankManagerConsoleApp/CustomerWaitingQueue.swift
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
- BankManagerConsoleApp/BankManagerConsoleAppTests/CustomerWaitingQueueTests.swift
안녕하세요 Steven! @stevenkim18 
와이 & 비모입니다.
은행창구 매니저 Step1 PR 전송합니다!
2주간  잘 부탁드립니다 😆
---
`T`와 `Element`를 제네릭 타입 선언시 많이 사용한다고 알고 있었습니다. 그 중에서 큐 타입을 구현할때 어떤 것을 써야 할 까 고민이 되어서 둘의 차이점을 찾아 보았습니다.
`T`는 제네릭 타입을 선언할 때 일반적으로 사용되는 관례적인 이름이고, `Element`는 컬렉션 또는 자료구조에서 개별 요소를 나타내는 데에 사용되는 관례적인 이름이라는 차이점을 알았습니다.
저희는 큐 라는 자료구조를 구현하는 것이기 때문에 `Element`를 사용하기로 결정했습니다.
저희는 `BankManagerConsoleApp`내에 `Queue`를 구현했습니다. 그리고 `Queue`의 기능을 테스트 하기 위해 `Test navigator`에서 새로운 `Unit Test Target - Unit Testing Bundle`을 추가했습니다. 기존에는 이것만으로 테스트를 진행할 수 있었으나, `XCode 14.3` 부터는 해당 `Scheme`에 대해 `Autocreated`된 `test`를 활용하는 것으로 바뀌었습니다. `Autocreated`된 `Test Plan`은 저희가 추가한 `Unit Testing Bundle`을 자동으로 인식하지 못했기 때문에, 해당 `Test Plan`에 `target`으로 앞서 생성한 `Unit Testing Bundle`을 추가했습니다. 이렇게 target을 추가하는 경우 `xctestplan` 파일이 생성되고, 해당 파일은 `File …
> 은행창구 매니저 [STEP 1] yyss99(와이), 비모

- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleApp.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/BankManagerConsoleAppTests.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/xcshareddata/xcschemes/QueueTests.xcscheme
- BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
- BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
- BankManagerConsoleApp/BankManagerConsoleAppTests/LinkedListTests.swift
- BankManagerConsoleApp/BankManagerConsoleAppTests/NodeTests.swift
- BankManagerConsoleApp/BankManagerConsoleAppTests/QueueTests.swift
@delmaSong  안녕하세요~~ hoon, minsup 조 입니다.😆
step1 많은 고민을 통해 완성을 했습니다. step1부터 쉽지 않았던 것 같아요.
xcode 버전도 달라 환경 설정에 많은 시간을 투자했습니다🥲
많은 조언 부탁드립니다. 감사합니다!!!
- `LinkedList`의 `removeAll()` 메소드를 구현하던 중 의문이 들었습니다.
> * 모든 노드를 순회하며 `nil`을 할당해서 메모리에서 해제시켜야 하는가?
> * 첫 노드만 `nil`을 할당하면 연결된 모든 노드들이 메모리에서 자동으로 해제되는가?
질문의 해답을 찾기 위해 직접 실험을 해보았습니다. head에 nil을 할당하면 연쇄적으로 연결된 모든 노드들이 메모리에서 해제되는 것을 확인했습니다.
```swift
mutating func removeAll() {
head = nil
tail = nil
}
```
`LinkedList`를 사용하여 새로운 `Node`가 추가되면 기존에 있던 `Node`의 `next` 프로퍼티를 통해 다음 `Node`를 참조합니다. 이렇게 각각의 `Node`는 다음에 오는 `Node`를 참조하고 있고 참조하는 `Node`가 없는 경우 `nil`을 가지고 있습니다. 첫 `Node`는 `head`가 참조하고 있습니다. `removeAll()` 메소드를 사용하여 각각 노드를 참조하고 있는 `head`와 `tail`에 `nil`을 할당하면 앞의 `Node`를 참조하고 있던 다음 `Node` 객체의 `reference count`는 0이 되어 메모리에서 해제됩니다. 그러므로 앞에 있던 `Node`부터 순차적으로 …
> 은행창구 매니저 [STEP 1] hoon, minsup
